### ISSUE TITLE
MetaCyc  reaction, compound CURIEs don't resolve and pathway prefix missing.

### ISSUE THREAD

**Issue by hrshdhgd** [biopragmatics/bioregistry#1008]
I'm a little new to this so I may not be explaining the issue properly. For this, I apologize in advance. 

Now `bioregistry.io/CHEBI:15377` resolves to `https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15377`. We could not find an equivalent resolution for `metacyc.compound` or `metacyc.reaction`. The prefixes exist in bioregistry but the IDs do not resolve.

Examples
======= 

Reaction
---------
In Metacyc, the reaction [seen here](https://metacyc.org/META/NEW-IMAGE?object=%2b-BORNEOL-DEHYDROGENASE-RXN&redirect=T) would have a bioregistry based CURIE as `metacyc.reaction:1.1.1.198` (1.1.1.198 is actually the EC number, so I don't know if this is correct). When I lookup `bioregistry.io/metacyc.reaction:1.1.1.198`, it takes me to `https://metacyc.org/META/NEW-IMAGE?type=REACTION&object=1.1.1.198` which does not seem correct.

Compound
----------
Here's an example of a compound: https://metacyc.org/compound?orgid=META&id=%2b-5-oxo-1-2-campholide

The problem here is a little different. There is a BioCyc ID (`+-5-oxo-1-2-campholide`) but no ID that would form a CURIE (metacyc.compound:XXXX). Would you have any possible solution to this?

Pathways
----------

- The prefix `metacyc.pathway` does not seem to exist in bioregistry. Could we add this?
- An example for a pathway would be: [`12DICHLORETHDEG-PWY`](https://metacyc.org/META/NEW-IMAGE?object=12DICHLORETHDEG-PWY&redirect=T). Here the pathway ID (`1,2-dichloroethane degradation`) would not follow our standard CURIE pattern. Any suggestions? 

All 3 (reaction,  compound and pathways) have BioCyC IDs but then they're not represented as `ABCD:1234` format we all prefer. 

cc: @cmungall

**Comment by cthoyt** [comment]
Hi @hrshdhgd can you please break this up into multiple self-contained issues so we can discuss them independently?

**Comment by hrshdhgd** [comment]
#1009 

#1010

#1011

**Comment by cthoyt** [comment]
closing in favor of split issues
