### ISSUE TITLE
Metacyc pathway does not have a prefix in bioregistry.

### ISSUE THREAD

**Issue by hrshdhgd** [biopragmatics/bioregistry#1011]
Continued from #1008 

- The prefix `metacyc.pathway` does not seem to exist in bioregistry. Could we add this?
- An example for a pathway would be: [`12DICHLORETHDEG-PWY`](https://metacyc.org/META/NEW-IMAGE?object=12DICHLORETHDEG-PWY&redirect=T). Here the pathway ID (`1,2-dichloroethane degradation`) would not follow our standard CURIE pattern. Any suggestions? 

All 3 (reaction,  compound and pathways) have BioCyC IDs but then they're not represented as `ABCD:1234` format we all prefer.

**Comment by cmungall** [comment]
@hrshdhgd this one is straightforward. The CURIE would be `metacyc.pathway:12DICHLORETHDEG-PWY`. This is perfectly fine. `1,2-dichloroethane degradation` is the label. This is a straightforward new prefix request.

There are likely more here for metacyc for other types: organism, media

**Comment by cthoyt** [comment]
Great, then feel free to use the new prefix issue template to get started

**Comment by hrshdhgd** [comment]
#1012
