### ISSUE TITLE
Add prefix mavedb

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#1045]
### Prefix

mavedb

### Name

Multiplexed Assays of Variant Effect Database

### Homepage

https://www.mavedb.org

### Source Code Repository

bioregistry

### Description

Some IDs may represent experiment sets, e.g. https://www.mavedb.org/#/experiment-sets/urn:mavedb:00000011

Others represent genomic regions (specifically deep mutational scans thereof) e.g. https://www.mavedb.org/#/experiment-sets/urn:mavedb:00000011-a

### Example Local Unique Identifier

00000011-a

### Regular Expression Pattern for Local Unique Identifier

^\S+$

### URI Format String

https://www.mavedb.org/#/experiments/urn:mavedb:$1

### Contributor Name

Chris Mungall

### Contributor GitHub

cmungall

### Contributor ORCiD

0000-0002-6601-2165

### Contributor Email

cjmungall@lbl.gov

### Contact Name

Alan Rubin

### Contact Email

alan.rubin@wehi.edu.au

### Additional Comments

This is an interesting one as the full IDs as they appear on the page are of the form `urn:mavedb:00000011-a` suggesting this is the preferred URI expansion for identification purposes. However, mavedb hasn't been registered with IANA https://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml

**Comment by cthoyt** [comment]
thanks @cmungall! I've added a bit more information in the PR and merged it.
