### ISSUE TITLE
Merge resource GlyGen into GlyTouCan

### ISSUE THREAD

**Issue by katewarner** [biopragmatics/bioregistry#1084]
### Redundant Prefix

glygen

### Target Prefix

glytoucan

### Explanation

The local unique identifier in the GlyGen prefix is actually a GlyTouCan ID, as we use these IDs to identify Glycans in GlyGen.

### Contributor ORCID

0000-0001-8705-181X

**Comment by bgyori** [comment]
Hi @katewarner, I think this makes sense. Interestingly, two other registries, Fairsharing, and Integbio also have separate entries for GlyGen and GlyToucan. In any case, what we could do is, keep the `glytoucan` prefix, but add `glygen` as a synonym prefix, and also list GlyGen as a "provider" for GlyToucan IDs.

**Comment by matentzn** [comment]
From the little bit of information in this issue the complete solution comes down to the question of whether the org behind https://glygen.org/ (@jeet-vora) agrees with the assertion that the local id corresponds to a GlyTouCan ID. Right now, both glytoucan and glygen are registered as separate “semantic spaces” covering the _same exact local ID space_ (as far as I can quickly see from the regex rules in both records):

https://bioregistry.io/registry/glygen
https://bioregistry.io/registry/glytoucan

If @jeet-vora agrees that the local ids are in fact all glytoucan ids IMO the course of action should be to:

1. Remove the glygen record entirely
2. Add the glygen prefix as a prefix synonym to the glytoucan record (as @bgyori suggests)
3. Add glygen.org as an alternative resolver (uri_prefix_synonym)
4.  While you are at it, add a point of contact to the glytoucan record

**Comment by bgyori** [comment]
Thanks @matentzn, the PR I opened here https://github.com/biopragmatics/bioregistry/pull/1109 implements what you are suggesting.
