### ISSUE TITLE
reactome pathway viewer CURIE expansion support prefix 

### ISSUE THREAD

**Issue by sierra-moxon** [biopragmatics/bioregistry#1085]
### Prefix

reactome.pathway

### Name

Reactome

### Homepage

https://reactome.org/

### Source Code Repository

https://github.com/reactome

### Description

REACTOME is an open-source, open access, manually curated and peer-reviewed pathway database. 
Founded in 2003, the Reactome project is led by Lincoln Stein of [OICR](http://oicr.on.ca/), Peter D’Eustachio of [NYU Langone Health](https://nyulangone.org/), Henning Hermjakob of [EMBL-EBI](http://www.ebi.ac.uk/), and Guanming Wu of [OHSU](http://www.ohsu.edu/).

### License

https://github.com/reactome/reactome2py/blob/master/LICENSE

### Publications

https://reactome.org/cite

### Example Local Unique Identifier

R-MMU-5655466

### Regular Expression Pattern for Local Unique Identifier

R-[A-Z]{3}-\d+

### URI Format String

https://reactome.org/PathwayBrowser/#/$1

### Wikidata Property

[_No response_]

### Contributor Name

Sierra Moxon

### Contributor GitHub

sierra-moxon

### Contributor ORCiD

0000-0002-8719-7760

### Contributor Email

smoxon@lbl.gov

### Contact Name

Peter D’Eustachio

### Contact ORCiD

0000-0002-5494-626X

### Contact GitHub

deustp01

### Contact Email

deustp01@med.nyu.edu

### Additional Comments

reactome already has a prefix `reactome` that refers to a specific detail page at reactome, e.g.
https://www.reactome.org/content/detail/R-MMU-5655466

using the same identifier, you can get a different view, e.g. https://reactome.org/PathwayBrowser/#/R-MMU-5655466

this request is to add a "dot extension" to provide the secondary expansion for the same "source".
e.g. `reactome.pathway` - expands_to -> "pathway page" vs. `reactome` - expands_to -> "detail page".

I am not sure if this means we need to edit the basic `reactome` prefix to support "dot extension" syntax?  (e.g. does `reactome` need to change to `reactome.detail` to be consistent? - preference is that it does not change).

**Comment by cthoyt** [comment]
This isn't the right way to accomplish this - each Bioregistry prefix corresponds to a semantic space, not to a type of resolution. The way to add multiple different kinds of resolution is to curate in the `"providers"` slot. For example, see the "Extra Providers" section for ChEBI: https://bioregistry.io/chebi. The `chebi-img` provider lets you redirect to an image based on the molecule, so 

- https://bioregistry.io/chebi:138488 redirects to the main page
- https://bioregistry.io/chebi:138488?provider=chebi-img redirects to the image

I can update the PR to accomplish this

**Comment by cthoyt** [comment]
See the updates in the PR, you can decide what the provider code is. Now the Reactome page's providers will look like this:

<img width="951" alt="Screenshot 2024-04-10 at 08 46 52" src="https://github.com/biopragmatics/bioregistry/assets/5069736/ee321f2e-ffef-43b2-9037-9aed3e70aa0c">

**Comment by sierra-moxon** [comment]
Thanks! this reminds me of the Alliance ["page" approac](https://github.com/alliance-genome/agr_schemas/blob/686f874ccac7dde088ed612721266e3fc741c00f/resourceDescriptors.yaml#L24)h in their resource_descriptor file.
