### ISSUE TITLE
Bioregistry hit project size limit on PyPI

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#1100]
On the automated update on April 17th, 2024, we finally hit the project size limit for PyPI. Here's the error log from the CI attempt to upload it to PyPI:

> ERROR HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/. Project size too large. Limit for project 'bioregistry' total size is 10 GB. See https://pypi.org/help/#project-size-limit

A few options for going forward:

1. Remove some older versions, maybe come up with a schedule so after 1 year, only 1 upload per month is kept
2. Remove some old ones, and then make the update schedule less frequent (maybe once per week instead of nightly)
3. Ask PyPI for increase in size? I don't think this is necessarily the best

In parallel, it might be worth checking if we can reduce the data that's packaged. For example, it's still nice to keep raw data in version control, but maybe we don't need raw data in the package.

**Comment by matentzn** [comment]
Wow! I think package size probably hast to be limited to be long term sustainable. Never knew about this limit!

**Comment by cthoyt** [comment]
I just deleted about 50 old versions (evenly spaced out days). Between that, changing updates to weekly, and reducing the size, this should be good until then end of the year when I'll be back and can come up with a more long-term solution
