### ISSUE TITLE
Add prefix biofactoid

### ISSUE THREAD

**Issue by jvwong** [biopragmatics/bioregistry#1106]
### Prefix

biofactoid

### Name

Biofactoid

### Homepage

https://biofactoid.org/

### Source Code Repository

https://github.com/PathwayCommons/factoid

### Description

Biofactoid is a resource of structured information describing biological pathways, assembled from author-curated results in papers. Each pathway is assigned an identifier.

### License

CC0 1.0 Universal

### Publications

doi: 10.7554/eLife.68292

### Example Local Unique Identifier

5df17c41-acb7-4c42-a37b-fe323688bc64

### Regular Expression Pattern for Local Unique Identifier

^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$

### URI Format String

https://biofactoid.org/document/$1

### Contributor Name

Jeffrey Vincent Wong

### Contributor GitHub

jvwong

### Contributor ORCiD

0000-0002-8912-5699

### Contributor Email

jeffvin.wong@utoronto.ca

**Comment by bgyori** [comment]
Hi @jvwong! Thanks, actually, Biofactoid is already registered here: https://bioregistry.io/registry/biofactoid. Looking at the data you entered, I think everything is there on the existing record, though the description is slightly different. Should we update any of the fields?

**Comment by jvwong** [comment]
@bgyori you appear to be some kind of mind reader! Looks good to me!
