### ISSUE TITLE
PURLs for some resources not resolving

### ISSUE THREAD

**Issue by bgyori** [biopragmatics/bioregistry#1123]
The following resources use PURLs as their default URI but these aren't resolving correctly:
- [InterPro](https://bioregistry.io/registry/interpro) with pattern `http://purl.obolibrary.org/obo/IPR_$1`, e.g., http://purl.obolibrary.org/obo/IPR_IPR016380 resolves to http://www.berkeleybop.org/ontologies/IPR_IPR016380 yielding a 404 error
- [LBO](https://bioregistry.io/registry/lbo) with pattern `http://purl.obolibrary.org/obo/LBO_$1` e.g., http://purl.obolibrary.org/obo/LBO_0000487 resolves to http://www.berkeleybop.org/ontologies/LBO_0000487 yielding a 404 error
- [PECO](https://bioregistry.io/registry/peco) with pattern `http://purl.obolibrary.org/obo/PECO_$1` e.g., http://purl.obolibrary.org/obo/PECO_0007114 resolves to https://ontobee.org/ontology/PECO?iri=http://purl.obolibrary.org/obo/PECO_0007114 yielding a Term Not Found error on Ontobee

@cmungall given the first two (InterPro and LBO) are related to berkeleybop.org, do you know what the issue could be? Who would be able to help with the Ontobee issue related to PECO?

**Comment by matentzn** [comment]
`http://purl.obolibrary.org/obo/{X}` redirects by default to `http://www.berkeleybop.org/ontologies/` for historical reasons. 

1. LBO and InterPro are both not OBO Foundry ontologies. Because of the above, their PURLs redirect to berkeley
2. [PECO](https://bioregistry.io/registry/peco) issue: https://github.com/Planteome/plant-experimental-conditions-ontology/issues/137. You can chime in there.

**Comment by bgyori** [comment]
Thanks @matentzn! Just to clarify: so LBO and InterPro are _not_ expected to be resolvable through berkeleybop.org? In that case, we could use the BioPortal to resolve these since there are working URLs there.

**Comment by matentzn** [comment]
> Thanks @matentzn! Just to clarify: so LBO and InterPro are not expected to be resolvable through berkeleybop.org? In that case, we could use the BioPortal to resolve these since there are working URLs there.

From the bioregistry perspective, you can, and should! But you won't be able to get the actual PURLs (`http://purl.obolibrary.org/obo/{X}`) to redirect. 

So for the `uri_prefix` you can use Bioportal, put you should maintain the `uri_prefix_rdf` to be the `http://purl.obolibrary.org/obo/{X}`.

**Comment by bgyori** [comment]
These are fixed in #1119 with the approach of preserving `rdf_uri_prefix` PURLs while updating the `uri_prefix` to working resolver URLs.

**Comment by cmungall** [comment]
Interpro isn’t an ontology! It shoukd just resolve to the interpro site
