### ISSUE TITLE
Add alliancegenome.org as provider a for all NHGRI MODs

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#1125]
For each of

* wormbase
* flybase
* rgd
* mgi
* zfin
* xenbase
* sgd

Add an alternative resolver to https://www.alliancegenome.org/

Note: in time some of these MODs may wish to 

I am currently discussing a generic resolver, as we want to avoid `{wormbase,flybase,...}.{gene,allele,variant,transgene}` cross-product explosion pf prefixes

**Comment by bgyori** [comment]
Thanks @cmungall, we will add alliancegenome.org as a provider for these databases

**Comment by bgyori** [comment]
Hi @cmungall, after a review of the resources you listed, we found that all of them, except `xenbase` already use alliancegenome.org as a provider. This means you can resolve e.g., SGD entries via the Bioreigsty as https://bioregistry.io/sgd:S000002493?provider=agr (i.e., by giving the provider=agr parameter to the resolver). So for now, the only action needed is adding a provider for xenbase.

**Comment by cmungall** [comment]
This part is particularly important:

> I am currently discussing a generic resolver, as we want to avoid {wormbase,flybase,...}.{gene,allele,variant,transgene} cross-product explosion pf prefixes

Unfortunately the current resolver assumes everything is a gene. Try this

https://bioregistry.io/wb:WBVar00241923?provider=agr

"Page Not Found"

Although genes are the most important, the Alliance will ultimately have many different kinds of entities

I'm hoping bioregistry doesn't inherit the antipattern from identifiers.org where resources were assumed to have only one type, and then new types added ad-hoc, following the `<DB>.<TYPE>` pattern, with the exception of the main type being `<DB>`. Meanwhile, a large section of the community use `<DB>:` as the prefix for *all* types.

See also:

- #65

**Comment by bgyori** [comment]
I see, I don't think we currently have any restriction on the type of ID that can be resolved via `agr` for these resources so the resolver would just have to be updated on the alliancegenome.org side to allow IDs like WBVar00241923.

I am not sure what the perfect solution is for the `<DB>.<TYPE>` issue or if there is even a one size fits all approach that is appropriate for all resources.
