### ISSUE TITLE
Update BioSystems

### ISSUE THREAD

**Issue by egonw** [biopragmatics/bioregistry#1154]
### Prefix

biosystems

### Explanation

The original website was phased out in 2022. The new website URL is: https://www.ncbi.nlm.nih.gov/Structure/biosystems/docs/biosystems_about.html

And the new URI pattern is: https://pubchem.ncbi.nlm.nih.gov/pathway/BSID:$1

### Contributor ORCID

0000-0001-7542-0286

**Comment by bgyori** [comment]
Thanks, @egonw I made these changes on the linked PR.
