### ISSUE TITLE
Update regular expression pattern for COCONUT

### ISSUE THREAD

**Issue by CS76** [biopragmatics/bioregistry#1176]
### Prefix

COCONUT

### New Regular Expression Pattern

```
^CNP\\d{7}(\\.\\d+)?$
```

### Explanation

New coconut identifiers are postfixed with dot notation
For example, CNP0018459.2 to denote a stereo variant

Also, the URL is now updated to the following
```
sh:namespace "https://coconut.naturalproducts.net/compound/"^^xsd:anyURI
```

Example: https://coconut.naturalproducts.net/compounds/CNP0018459.2

### Contributor ORCID

0000-0002-2564-3243

**Comment by bgyori** [comment]
Thanks @CS76, I added the new pattern and also added an extra example ID to the `coconut` record.
