### ISSUE TITLE
Add prefix ncbiortholog

### ISSUE THREAD

**Issue by murphyte** [biopragmatics/bioregistry#1181]
### Prefix

ncbiortholog

### Name

National Center for Biotechnology Information

### Homepage

https://www.ncbi.nlm.nih.gov/gene/

### Source Code Repository

n/a

### Description

Database of one-to-one ortholog information provided by the NCBI as a subset of their Gene resource. Used for users to access ortholog information for over 1000 species of vertebrates and arthropods.

### License

US gov't public domain

### Example Local Unique Identifier

2

### Regular Expression Pattern for Local Unique Identifier

\d+$

### URI Format String

https://www.ncbi.nlm.nih.gov/gene/$1/ortholog/

### Contributor Name

Terence Murphy

### Contributor GitHub

murphyte

### Contributor ORCiD

0000-0001-9311-9745

### Contributor Email

murphyte@ncbi.nlm.nih.gov

### Contact Name

Terence Murphy

### Contact ORCiD

0000-0001-9311-9745

### Contact GitHub

murphyte

### Contact Email

murphyte@ncbi.nlm.nih.gov

### Additional Comments

We do not currently have the source code for our ortholog resource available publicly, although we are looking at how to split it off and make it available in the next year. We are now in the process of adding this tag to the INSDC list for use in annotations, so I'd like to mirror that tag in bioregistry.

**Comment by bgyori** [comment]
Hi @murphyte, thank you for the contribution! Looking at the new entry, my understanding is that the ortholog resource doesn't introduce a new space of identifiers, rather, it takes an NCBI/Entrez Gene ID (for which there is already a Bioregistry entry at https://bioregistry.io/registry/ncbigene) and _provides_ ortholog information for that gene. So in this case, introducing a new Bioregistry prefix may not be the appropriate approach. Rather, we could curate the NCBI Ortholog resource as a provider for NCBI Gene IDs. This would allow NCBI Orthologs to show up at https://bioregistry.io/registry/ncbigene under the providers section and also allows resolving NCBI Gene IDs to the ortholog provider via the URI pattern https://www.ncbi.nlm.nih.gov/gene/$1/ortholog/. Should I go ahead and do this?

**Comment by murphyte** [comment]
Ugh, I meant to make this plural. `ncbiorthologs`. I'll make some edits.

These pages are distinct from NCBI Gene, so it's similar to a resource like BGee that uses Ensembl IDs rather than reassigning their own IDs, but provides distinct data:
https://www.bgee.org/gene/ENSG00000175899

This is pretty common practice for resources that compute new data based on existing datasets.

So in that same vein, these two URLs provide distinct data and content:
https://www.ncbi.nlm.nih.gov/gene/2/ortholog
https://www.ncbi.nlm.nih.gov/gene/2

providing `ncbigene:2` on an annotated gene feature conveys that ncbigene record is for the specific gene in question.
providing `ncbiorthologs:2` (a human gene) on say a giraffe gene feature conveys that that record is for the set of orthologs that includes the giraffe gene. 

We're going to use the `ncbiorthologs:2` dbxref on new GenBank submissions to convey this orthology information.

Does that make sense?

**Comment by bgyori** [comment]
Thank you for the additional info! I think what you are describing would still be more appropriate as a new _provider_ for an existing prefix rather than a new prefix. The example with BGee is also similar: rather than introduce a new identifier space, they resolve Ensembl IDs and provide custom data on those. This is reflected in the Bioregistry (see https://bioregistry.io/registry/ensembl) as below, in the `bgee` row:

![image](https://github.com/user-attachments/assets/1e2523fb-5b7e-4fe8-862b-29479b204438)

I am curious about additional perspectives from @cmungall, @matentzn, @cthoyt if you have further thoughts about how to proceed!

**Comment by murphyte** [comment]
bgee also has its own listings for bgee.gene, bgee.organ, bgee.family, and bgee.stage):
https://bioregistry.io/registry/bgee.gene
if you search the registry for bgee, those are the ones you find and not the list of "extra providers" under Ensembl Gene.

and gnomad also shows up as its own entry:
https://bioregistry.io/registry/gnomad

More critically, this does not work: https://bioregistry.io/bgee:ENSG00000139618

So what's the point of the "extra providers"? I think it might relate to a question I brought up with @cmungall recently on e-mail, related to this page:
https://bioregistry.io/registry/orthodb

Which says:
> This resource is a provider. This means that while it may have its own prefix, it actually reuses the identifiers provided by the [uniprot](https://bioregistry.io/registry/uniprot) prefix. For all use cases, you should use [uniprot](https://bioregistry.io/registry/uniprot) instead of orthodb.

While there does seem to be a problem with the OrthoDB URL not resolving to a specific page that I couldn't readily figure out how to solve, I disagree with the statement that one should use `[uniprot]`. OrthoDB is not a provider of UniProt data. They're a provider of their own data that happens to sometimes (not always) use UniProt identifiers. It's the same deal with NCBI Orthologs.

**Comment by murphyte** [comment]
> An alternative provider such as bgee can be invoked by adding the provider parameter as: [https://bioregistry.io/ensembl:ENSG00000139618?provider=bgee](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbioregistry.io%2Fensembl%3AENSG00000139618%3Fprovider%3Dbgee&data=05%7C02%7Cmurphyte%40ncbi.nlm.nih.gov%7C85a293a8327f45d8f4a108dcd0ff636b%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638615042530735251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=jOMf9Mk0MvpF4W5v8BLQazv6Lb1QorIbbXgJA1EMoiA%3D&reserved=0) which I think is what you were looking for.

My usage is to have GFF3 files that include: `Dbxref=ncbiorthologs:2`, and users can resolve `ncbiorthologs` to a resource and URL. That has no indication of NCBI Gene (nor should it), so how can it be resolved through bioregistry.io? The same seems true for that `bgee` URL when needing to include ensembl, and that seems even a bit worse since the resources are completely different groups. 

Maybe I'm confused about the goal for bioregistry.io. I'm focused on resolving the dbs themselves, primarily to be able to interpret Dbxref attributes, and you seem to have a focus on the identifiers themselves.

**Comment by bgyori** [comment]
Right, the distinction seems to be between thinking about
1. ncbiorthologs:2 from the perspective of resolution i.e., mapping the CURIE to a URL (which is what you are looking for), where `ncbiortholog` is just a shorthand for a URL pattern and it doesn't really matter what `2` is as long as it can be resolved.
2. ncbiorthologs:2 from the perspective of what real entity `2` refers to with respect to identifier provider resources, the identifiers they assign to entities, and data integration across such resources.

As we clearly see from your use case and other examples like BGee the two often overlap in complex ways. If we were to make a new prefix for `ncbiortholog`, it would solve 1 but be problematic in terms of 2. I am usually pragmatic in these things and would be open to doing that but - at the risk of not taking immediate action - I think this problem is general enough that input from the folks I tagged above or others thinking about these issues would actually be useful.

**Comment by murphyte** [comment]
Yep, discussion is good. These decisions have long-lasting repercussions and I can be (slightly) patient. Although I have already opened some initial implementation tickets for work at NCBI, so I can't be _too_ patient ;).

I can also make the argument that the `2` here does refer to an ortholog entity. It happens to also refer to a related gene entity, and there's a large set of identifiers that refer to that same ortholog entity. But they are orthogonal entities. There's a certain convenience in reusing identifiers for distinct but related entities because it makes it easier to join data across resources. There are disadvantages as well, and somewhere down the line we may have to add an additional entity space into this resource. But I'm just working on baby steps here first.

**Comment by bgyori** [comment]
Actually, your latest comment puts things in a different perspective, I might have misunderstood something.

> I can also make the argument that the 2 here does refer to an ortholog entity. It happens to also refer to a related gene entity, and there's a large set of identifiers that refer to that same ortholog entity.

I see, so actually, `2` is actually a new identifier that is identifying an ortholog entity but it inherits the identifier value from - at least in this case - a human NCBI Gene ID `2` that is part of this ortholog group.

Looking at this example further, this group contains genes such as https://www.ncbi.nlm.nih.gov/gene/418251/ and https://www.ncbi.nlm.nih.gov/gene/465372/, etc. but the ortholog entry associated with these genes is always https://www.ncbi.nlm.nih.gov/gene/2/ortholog.

If this is correct, then I am actually convinced now that this should be a new prefix :)

**Comment by murphyte** [comment]
> If this is correct, then I am actually convinced now that this should be a new prefix :)

yep, that's correct.
I was also thinking it was implemented such that https://www.ncbi.nlm.nih.gov/gene/465372/ortholog would work in a way that's synonymous, but I see that's not the case. That's probably just me mis-remembering the implementation details. In practice we always use the "anchor" GeneID for the URL, and it really is an ortholog entity.

Last question: `ncbiortholog` or `ncbiorthologs`? The page is labeled as "NCBI Orthologs", but perhaps that's an odd convention for a Dbxref tag. Thoughts?

**Comment by bgyori** [comment]
I would go with `ncbiortholog` as each identifier represents a single ortholog group.

**Comment by murphyte** [comment]
ok, thanks. That's a very reasonable argument. We'll do that.

**Comment by cmungall** [comment]
Let's just think of the precedent for a moment here.

Are we opening the floodgates to

- `{$geneId,$proteinId}/{GOFunction,Phenotypes,Diseases,DrugTargets,Variants,Paralogs,Orthologs,...}`
- `$diseaseId/{Genes,Variants,Phenotypes,....}`
- `$goFunctionId/{Genes,Proteins}/$speciesId`
- ....

Where multiple different databases can lay claim to each of the function groups, disease groups, etc. Look at any knowledge base portal, you will see for any entity there is a long list of kinds of association tables each with their own html anchor tag, constituting an "id" for a set of associations. 

If we do this, what are the governance rules? Can GO claim `ncbigenefunction` with `ncbigenefunction/2` being all A2M functions curated by GO? Or would substrings `ncbi` be implicitly claimed? Does bioregistry really want the burden of maintaining all of these association sets?

I would prefer this was discouraged, and that we come up with another way to register association sets that are uniquely identifier by a function like `orthologOf(g)` that won't involve proliferating prefixes

**Comment by murphyte** [comment]
don't be deceived here by the structure of the URL. This isn't a case where you can simply add `/ortholog/` to the end of any `ncbigene` URL and get a page. It won't work. The content on the ortholog pages is really a distinct entity. The URL was set up this way for somewhat technical reasons.

> a function like `orthologOf(g)`

That's exactly what we need here, and the only formalized way I see to do it is with an independent prefix. The only formalized attribute we have to work with is `Dbxref=prefix:value`, in either GFF3 or INSDC flatfile formats. The entity value is fixed, so it's gotta be a distinct prefix. Using `ncbigene` is wrong -- it refers to the wrong entity and would be an error to include on a gene feature from a different organism than that ncbigene record. `ncbigene.ortholog` is a little closer, but I would find that a bit confusing because these Dbxrefs will appear on gene features that have no corresponding `ncbigene` entry. As I said, these pages aren't simply `ncbigene` URLs with `/ortholog/` tacked on the end.

> Or would substrings `ncbi` be implicitly claimed?

This is an important point, but orthogonal. For reasons unknown to me, the various NCBI resources I see in bioregistry.io have a mix of `ncbi`, `ncbi.` or no leader. I think most of these were set up (I think mostly in identifiers.org, and imported to bioregistry.io) without consultation with anyone at NCBI, and apparently done ad hoc given the variation in styles. `ensembl` and `uniprot` are more consistent, mostly using the `.` version, but with some deviation (`uniref`, `uniparc`, `ensemblglossary`). I do think the leading strings `ncbi`, `ensembl`, and `uniprot` should be implicitly (or explicitly) reserved for those providers, although I'm also not too concerned about another provider trying to usurp one of those.

Considering `ncbiortholog` vs `ncbi.ortholog`, within INSDC, [db_xref prefixes](https://www.ncbi.nlm.nih.gov/genbank/collab/db_xref/) have a variety of styles including some types of punctuation (and even a space in one case), but nothing currently with a period. I have some concerns that our indexing system wouldn't like the period -- the one with the space behaves oddly for search, and I suspect it would do the same thing for a period. So for INSDC purposes I do want to use `ncbiortholog`, but if you really want you could set it up as `ncbi.ortholog` with `ncbiortholog` as an alternative prefix.

**Comment by bgyori** [comment]
@cmungall while initially my thinking was along the lines of your comment, my understanding now is that `ncbiortholog` is genuinely a new identifier space for gene ortholog groups (see https://github.com/biopragmatics/bioregistry/issues/1181#issuecomment-2339208936), it's just that the form of the URL pattern and the fact that the ortholog group identifiers are anchored to the gene identifier of one gene in the group make this less obvious.
