### ISSUE TITLE
Add provider for Developing Human Brain Atlas

### ISSUE THREAD

**Issue by hkir-dev** [biopragmatics/bioregistry#1191]
### Prefix

dhba

### URI Format String

https://purl.brain-bican.org/ontology/dhbao/DHBA_$1

### Contributor ORCID

0000-0002-3315-2794

### Explanation

[Ontology version of the DHBA](https://github.com/brain-bican/developing_human_brain_atlas_ontology) deployed to OLS

**Comment by bgyori** [comment]
Thanks @hkir-dev! Quick question: I am trying out the URI format above with the curated example ID for DHBA: https://purl.brain-bican.org/ontology/dhbao/DHBA_10153 but it is not resolving. Is the website up?

**Comment by bgyori** [comment]
Never mind, a minute later now it's working and resolving to OLS.
