### ISSUE TITLE
GO Registry

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#12]
http://www-legacy.geneontology.org/doc/GO.xrf_abbs

This thing claims the upstream version of this file is actually on github at:

https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

**Comment by cmungall** [comment]
This is correct. We could also export to a different format if we want to come up with a standard here.

**Comment by cthoyt** [comment]
It would be interesting to define a JSON schema or YAML schema for what it means to be a "registry"

I actually already finished this a long time ago (see https://github.com/bioregistry/bioregistry/blob/main/src/bioregistry/align/go.py). There were just a few things that were a lot of work to figure out what they were and I never finished, I took the 80/20 rule with a lot of these

**Comment by cthoyt** [comment]
This has been finished for a long time
