### ISSUE TITLE
How to curate the Genomics 2 Proteins (G2P) Portal?

### ISSUE THREAD

**Issue by nagutm** [biopragmatics/bioregistry#1224]
This issue is regarding the [G2P](https://g2p.broadinstitute.org/) resource ([PMID](https://pmc.ncbi.nlm.nih.gov/articles/PMC11466821/)) and whether to curate it in the Bioregistry, and if so, how?

Looking at an [example identifier](https://g2p.broadinstitute.org/gene/LDLR/protein/P01130) page and its URL: https://g2p.broadinstitute.org/gene/LDLR/protein/P01130, it appears to parse both UniProt and GeneCards identifiers. 

Should it be considered a provider for UniProt, GeneCards, or both?

Is it even possible to curate a resource like G2P in the Bioregistry that depends on identifiers from two different resources?

**Comment by cthoyt** [comment]
Put it as a provider for both. There are lots of resources that instead of using proper CURIEs, rely on regex matchers to differentiate between different semantic spaces. However, this doesn't stop us from curating it as a provider for each.

**Comment by bgyori** [comment]
Upon further review, the website is able to resolve `hgnc.symbol`-s but not `uniprot` IDs alone. So we should curate it as a provider for `hgnc.symbol`. This fits with the semantics of the resource as having genes as an entry point.
