### ISSUE TITLE
mycobank prefixes don't resolve

### ISSUE THREAD

**Issue by CarMoreno** [biopragmatics/bioregistry#1229]
I am testing the [`mycobank`](https://bioregistry.io/registry/mycobank) prefix and it does not resolve correctly. It seems that the correct prefix URI is now: [https://www.mycobank.org/page/Name%20details%20page/](https://www.mycobank.org/page/Name%20details%20page/ ) rather than [http://www.mycobank.org/Biolomics.aspx?Table=Mycobank&MycoBankNr_=](http://www.mycobank.org/Biolomics.aspx?Table=Mycobank&MycoBankNr_=)

Example: [mycobank:349124](https://www.mycobank.org/page/Name%20details%20page/349124)

**Comment by cthoyt** [comment]
Thanks @CarMoreno. PR coming up momentarily
