### ISSUE TITLE
Add prefix gtdb

### ISSUE THREAD

**Issue by ialarmedalien** [biopragmatics/bioregistry#1239]
### Prefix

gtdb

### Name

Genome Taxonomy Database

### Homepage

https://gtdb.ecogenomic.org

### Description

The Genome Taxonomy Database (GTDB) is an initiative to establish a standardised microbial taxonomy based on genome phylogeny.

### License

CC-BY-SA-4.0

### Publications

doi:10.1093/nar/gkab776|doi:10.1038/s41564-021-00918-8|doi:10.1038/s41587-020-0501-8|doi:10.1038/nbt.4229

### Example Local Unique Identifier

g__Prochlorococcus_A

### Regular Expression Pattern for Local Unique Identifier

^[cdfgops]__\w+\S+$

### URI Format String

https://gtdb.ecogenomic.org/tree?r=$1

### Contributor Name

AJ Ireland

### Contributor GitHub

ialarmedalien

### Contributor ORCiD

0000-0003-1982-9065

### Contact Name

Donovan Parks

### Contact ORCiD

0000-0001-6662-9010

**Comment by cthoyt** [comment]
thanks @ialarmedalien! your new record is merge in PR #1242. It'll be up with the next weekly re-deploy of the Bioregistry
