### ISSUE TITLE
Add prefix `dpvocab`

### ISSUE THREAD

**Issue by caufieldjh** [biopragmatics/bioregistry#1241]
### Prefix

dpvocab

### Name

Data Privacy Vocabulary

### Homepage

https://w3c.github.io/dpv/2.0/dpv

### Source Code Repository

https://github.com/w3c/dpv

### Description

The Data Privacy Vocabulary provides an ontology (classes and properties) and taxonomies of concepts to represent information regarding how personal data is processed in the form of an ontology or a knowledge graph.

### Publications

https://doi.org/10.48550/arXiv.2404.13426

### Example Local Unique Identifier

Duration

### URI Format String

https://w3id.org/dpv#Duration

### Contributor Name

Harry Caufield

### Contributor GitHub

caufieldjh

### Contributor ORCiD

0000-0001-5705-7831

### Contributor Email

jhc@lbl.gov

### Contact Name

Harshvardhan J. Pandit

### Contact ORCiD

0000-0002-5068-3714

### Contact GitHub

coolharsh55

### Contact Email

me@harshp.com

### Additional Comments

The resource itself specifies a preferred prefix of `dpv` but this is already claimed in Bioregistry by the Description of Plant Viruses (https://bioregistry.io/registry/dpv)

**Comment by cthoyt** [comment]
Thanks @caufieldjh. It's a shame about this conflict - W3C prefixes are pretty respectable, and the other one is not that important as far as I'm aware. However, this is a newly minted prefix, and W3C should also be more careful about this.

I also added a note to their repo https://github.com/w3c/dpv/issues/195 to clarify the license

**Comment by bact** [comment]
The SPDX License Identifier here is `W3C-20150513`.

Please refer to the comment at https://github.com/spdx/license-list-XML/issues/2600
