### ISSUE TITLE
Register FEMA and JECFA numbers

### ISSUE THREAD

**Issue by bgyori** [biopragmatics/bioregistry#1247]
Similar to #1246, encountered FEMA and JECFA numbers as cross-references for compounds.

FEMA: https://www.femaflavor.org/, e.g., 4667, unfortunately, the URLs don't use the ID but rather the name, e.g., https://www.femaflavor.org/flavor-library/24-ethyl-426-dimethyldihydro-135-dithiazine-mixture-isomers.

JECFA: https://apps.who.int/food-additives-contaminants-jecfa-database/, e.g, 2116, again, unfortunately, the URLs don't use the JECFA ID (but some other number that is completely different): https://apps.who.int/food-additives-contaminants-jecfa-database/Home/Chemical/6163. This actually appears in WikiData as P4852 (see external/wikidata/processed.json) but I believe the WikiData record confounds the numbers used in the URL with what is actually called a JECFA ID.

**Comment by nagutm** [comment]
I can look into this

**Comment by nagutm** [comment]
JECFA:
- Although the URL uses a different number than the JECFA ID, not all entries in this resource contain a specific JECFA ID [example 1](https://apps.who.int/food-additives-contaminants-jecfa-database/Home/Chemical/1370), [example 2](https://apps.who.int/food-additives-contaminants-jecfa-database/Home/Chemical/62) that is distinct from the one in the URL.
- Given this, I think that we can curate this in the bioregistry with the number in the URL as the main identifier.

FEMA:
- Although this resource provides references to the FEMA, JECFA and CAS numbers, none of these identifiers are resolvable through the URL. 
- Given that this is a notable resource, we could curate it with the name of the chemical as the main identifier and possibly add the FEMA number in the `example_extras` field.

**Comment by bgyori** [comment]
Thanks for looking into this @nagutm. I would approach this not from the perspective of the URI patterns (which seem to use arbitrary IDs that are not defined anywhere) but from the perspective of the actual FEMA and JECFA IDs (which are defined and appear in cross-references and therefore necessitate a prefix to be representable). So let's curate new prefixes for the FEMA/JECFA IDs and for the time being assume that there is no URI pattern to resolve these - unless of course we find a provider somewhere.

**Comment by bgyori** [comment]
After a bit more digging I actually found that WikiData has two different properties for JECFA, including this: https://www.wikidata.org/wiki/Property:P9557 ("JECFA number") which is the one we should be mapping to instead of P4852.

**Comment by bgyori** [comment]
Done in #1254 and #1255.
