### ISSUE TITLE
Invalid Contributor ORCiD causes 'Register new prefix' workflow to crash

### ISSUE THREAD

**Issue by nagutm** [biopragmatics/bioregistry#1261]
The current `contributor_orcid` field in the new prefix issue template is mandatory, but it doesn't handle invalid entries effectively. Specifically, users who do not have an ORCiD can enter something like "na". 

This was noticed in the following run: https://github.com/biopragmatics/bioregistry/actions/runs/11737450444/job/32698260677 

This causes the following error during the Update step of the workflow:

      - pydantic_core._pydantic_core.ValidationError: 1 validation error for Author orcid
        String should match pattern '^\d{4}-\d{4}-\d{4}-\d{3}(\d|X)$' [type=string_pattern_mismatch, input_value='na', input_type=str]
        
We could adopt one of the solutions below to address this issue and prevent this error from reappearing:
1. Make the Contributor ORCiD Field Optional
2. Add More Strict Backend Validation for ORCiD Field
3. Allow "N/A" or Similar Values to Indicate No ORCiD

**Comment by cthoyt** [comment]
Valid ORCID is a non-negotiable requirement.

**Comment by nagutm** [comment]
I have made 2 additional changes:

1. Updated the description of the Contributor ORCiD field in the issue template to stress the importance of providing a valid ORCiD and directing them to the registration page if they don't have one.

2. Update `bioregistry.gh.new_prefix` to catch validation errors for the contributor so that it returns None and continues to create a PR with the valid content.

**Comment by bgyori** [comment]
Okay, I think that makes sense. @nagutm one comment on #1260 is that when adding content manually, I would not add temporary placeholders for the email and ORCID. It would be better to leave those out and - since ORCID is required - have the tests explicitly fail. Then we would not merge the PR until a valid ORCID is provided and the tests pass.
