### ISSUE TITLE
Add prefix CHR

### ISSUE THREAD

**Issue by caufieldjh** [biopragmatics/bioregistry#1265]
### Prefix

chr

### Name

Chromosome Ontology

### Homepage

https://github.com/monarch-initiative/monochrom

### Source Code Repository

https://github.com/monarch-initiative/monochrom

### Description

The Chromosome Ontology, Chromo (abbreviation CHR), is an automatically derived ontology of chromosomes and chromosome parts.

### License

BSD-3

### Example Local Unique Identifier

chr:10090-chr10qC

### Contributor Name

Harry Caufield

### Contributor GitHub

caufieldjh

### Contributor ORCiD

0000-0001-5705-7831

### Contributor Email

jhc@lbl.gov

### Contact Name

Chris Mungall

### Contact Email

cjmungall@lbl.gov

**Comment by cthoyt** [comment]
@caufieldjh thanks for the submission! A few comments:

1. can you please provide a regular expression pattern for this? 
2. how stable do you think this ontology's identifiers are going to be?
3. Is the data really licensed using this software license? Can you clarify?
4. Is `chromo` also a synonym for this ontology?

**Comment by cthoyt** [comment]
RE #1212 @matentzn here's an example of an ontology developed using OBO tools, so the OWL file has auto-generated URIs like http://purl.obolibrary.org/obo/CHR_10090-chr1. Following previous ontology submissions, I still think the right thing to do is to add this as the URI format in this Bioregistry submission.

**Comment by matentzn** [comment]
My two $:

1. not `chromo`, no. 

> I expect the local IDs to be stable but the PURLs may change - relevant to https://github.com/biopragmatics/bioregistry/issues/1212 above.

I think @cmungall fully expects this to be submitted to OBO and in fact, he has asked as a dozen times to do it and no one ever did.. It is totally in scope though.

Agree with rest of Harry's comments, I guess we _could_ try to figure out the regex for chromosomal locations but maybe ``\d+-chr[a-zA-Z0-9.-]+` cutz it.

**Comment by cmungall** [comment]
Regexes:

C elegans: I mess with your system
D melanogaster: hold my beer
D miranda: errm…
