### ISSUE TITLE
Add prefix seed.subsystem

### ISSUE THREAD

**Issue by samseaver** [biopragmatics/bioregistry#1302]
### Prefix

seed.subsystem

### Name

The SEED

### Homepage

https://theseed.org/

### Source Code Repository

https://github.com/orgs/TheSEED

### Description

With the growing number of available genomes, the need for an environment to support effective comparative analysis increases. The original SEED Project was started in 2003 by the [Fellowship for Interpretation of Genomes (FIG)](http://thefig.info/) as a largely unfunded open source effort. Argonne National Laboratory and the University of Chicago joined the project, and now much of the activity occurs at those two institutions (as well as the University of Illinois at Urbana-Champaign, Hope college, San Diego State University, the Burnham Institute and a number of other institutions). The cooperative effort focuses on the development of the comparative genomics environment called the SEED and, more importantly, on the development of curated genomic data.

### License

MIT

### Publications

doi:10.1093/nar/gki866

### Example Local Unique Identifier

Biotin_biosynthesis

### Contributor Name

Sam Seaver

### Contributor GitHub

samseaver

### Contributor ORCiD

0000-0002-7674-5194

### Contributor Email

seaver@anl.gov

**Comment by cthoyt** [comment]
@samseaver can you check the seed prefix and let me know if these are the same? I believe it already covers this request
