### ISSUE TITLE
Add prefix mixs

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#151]
### Prefix

mixs

### Name

GSC Minimal Information about any Sequence

### Homepage

https://gensc.org/mixs/

### Description

The GSC family of minimum information standards (checklists) – Minimum Information about any (x) Sequence (MIxS). MIxS identifiers are for terms describing an aspect of an environmental sample.

### Example Local Unique Identifier

ph_regm

### Regular Expression Pattern for Local Unique Identifier

^\w+$

### URI Format String

http://gensc.org/ns/mixs/$1

### Contributor Name

Chris Mungall

### Contributor ORCiD

0000-0002-6601-2165

### Contributor GitHub

cmungall

### Additional Comments

Some things to be decided before granting

 - [ ] should the prefix be mixs, gsc.mixs, MIxS, MIXS, ...?
 - [ ] MIxS terms are most commonly identified by a short computable stable label, e.g ph_regm. The GSC CIG team are creating numeric identifiers, e.g. MIXS:0001056
       - Should we support both schemes?
       - If we do, should these be different prefixes? I would strongly recommend this. E.g. mixs.term:ph_regm, mixs:0001056. We can then have different regex patterns for both

Additional notes:

 - The http://gensc.org/ns/mixs/ will likely changes to a w3id.org URI that will also serve as a semweb identifier
 - It currently redirects to the tdwg wiki but this is I assume temporary

**Comment by cthoyt** [comment]
GSC is the nomenclature organization, so i would only say it should be included in the prefix if there are other closely related ID spaces granted by the same organization. 

I would advise against both schemes - prefixes are most appropriate for identifiers and not names, with the notable exception being HGNC gene symbols (which I don't personally agree with)

Extra note for next time: you don't need to include the prefix in the example identifier.

**Comment by cmungall** [comment]
Good point about both schemes, but I should note that the "names" like "ph_regm" are distinct from the full name such as "ph regimen". They function more like identifiers, perhaps analogous to something like metacyc reaction or pathway IDs that employ mnemonic "names". These are also what is currently in use in most databases like INSDC. But I will try and get other GSC folks to comment here

**Comment by cthoyt** [comment]
Hi @cmungall, I've made a few tiny updates and merged this. There are still some open questions so whenever you or @ramonawalls have some updates, feel free to DM me on slack, open a new issue, or make another PR yourself and we can take care of it together. Thank you for the submission! 🥳
