### ISSUE TITLE
Add provider for DOI

### ISSUE THREAD

**Issue by egonw** [biopragmatics/bioregistry#172]
### Prefix

doi

### Provider Format URL

https://scholia.toolforge.org/doi/$1

### Contributor ORCID

0000-0001-7542-0286

**Comment by cthoyt** [comment]
@egonw scholia would be much more convenient if it accepted `https://scholia.toolforge.org/$1:$2` because then it could be considered as a registry and metaprovider

**Comment by egonw** [comment]
Yeah, would be nice to have Scholia as compact identifier resolver indeed :) Thought: BridgeDb maps a number of prefixes to Wikidata properties...

cc @fnielsen @Daniel-Mietchen

**Comment by egonw** [comment]
See also https://github.com/biopragmatics/bioregistry/issues/176

**Comment by cthoyt** [comment]
> @egonw scholia would be much more convenient if it accepted `https://scholia.toolforge.org/$1:$2` because then it could be considered as a registry and metaprovider

Actually now that I think of it there isn't really a reason why we couldn't do this with the slash. I will make a new issue for including scholia as another registry
