### ISSUE TITLE
database field for mapping a prefix to the corresponding Wikidata property

### ISSUE THREAD

**Issue by egonw** [biopragmatics/bioregistry#176]
For example, `inchikey` would map to [P235](https://www.wikidata.org/wiki/Property:P235)

**Comment by cthoyt** [comment]
Already exists :)

See on http://bioregistry.io/registry/inchikey

<img width="955" alt="Screen Shot 2021-09-28 at 21 40 48" src="https://user-images.githubusercontent.com/5069736/135154834-6c6b633e-84cd-4ebf-b9eb-223cd9c4a111.png">

**Comment by egonw** [comment]
Sorry I missed that!
