### ISSUE TITLE
Add `neuroname` prefix for http rather than https urls

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#182]
http://bioregistry.io/registry/neuronames

only covers https urls, but there are hundreds of references with http URLs:

```
http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=
```

**Comment by cthoyt** [comment]
So have two different prefixes, one with HTTP and one with HTTPs?

This might finally be the reason we have to do more first-class support for additional providers

**Comment by matentzn** [comment]
My suggestion is like this:
1. we have two prefixes, one of which preferred
2. We connect them somehow with a "consider" relation
3. We help sources move to the _version_ with the preferred prefix

**Comment by cthoyt** [comment]
Yes, this is what the "synonyms" field is for. Since I've only ever seen it written as `neuronames`, I will suggest we keep it that way. Again this also comes back to the need for any IRI parsers to consider both http and https as the same, so I will make some unit tests for this
