### ISSUE TITLE
oboInOwl example is wrong and need two prefixes

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#183]
- [ ] http://www.geneontology.org/formats/oboInOwl#hasDbXref should be use in example, no DbXref (wrong).
- [ ] `oio` is another widely used prefix of http://www.geneontology.org/formats/oboInOwl#, but we still want `oboInOwl` to be default.

**Comment by cmungall** [comment]
Happy to deprecate one usage, we could do this over the course of a few months

**Comment by cthoyt** [comment]
If you do this, let me know which one you want to be canonical and I will make sure that's the preferred one in the bioregistry. Either way, the bioregistry can continue acting as a reference for both in case people encounter them in old artifacts.
