### ISSUE TITLE
Confused about how Namespace in Pattern works

### ISSUE THREAD

**Issue by dhimmel** [biopragmatics/bioregistry#191]
An example Human Disease Ontology ID is `DOID:0110974` and the prefix is `doid`, hence I agree that Namespace in Pattern is true at http://bioregistry.io/registry/doid

> ![image](https://user-images.githubusercontent.com/1117703/135313932-eec15c4c-0754-4330-8669-596c46a76ab9.png)

Why doesn't the example identifier include the `DOID:` prefix and is a bare `0110974` instead?

Now looking at EFO at http://bioregistry.io/registry/efo:

![image](https://user-images.githubusercontent.com/1117703/135314588-3d891d85-b0e2-466a-8bb4-88401826e90a.png)

Namespace in Pattern is false. This surprises me because I never see bare EFO IDs like `0005147`, but always `EFO:0005147`. How is EFO different than Disease Ontology such that namespace in prefix differs?

**Comment by bgyori** [comment]
As far as I know, and can tell based on providers, EFO IDs do not contain the namespace, they are just bare IDs. I do tend to agree that - despite the fact that Bioregistry can correctly resolve IDs even if the embedded namespace is not given - the Example Identifier should contain the namespace when it's part of the pattern.

**Comment by dhimmel** [comment]
> As far as I know, and can tell based on providers, EFO IDs do not contain the namespace, they are just bare IDs.

Can you comment more on this? Does providers refer to identifiers.org?

If we look in the [EFO OWL](https://github.com/EBISPOT/efo/releases/download/v3.34.0/efo.owl) (which imports terms for other ontologies), I see the following snippets providing IDs to terms:

```xml
<oboInOwl:id>EFO:0003885</oboInOwl:id>
<oboInOwl:id>MONDO:0012237</oboInOwl:id>
<oboInOwl:id>DOID:7551</oboInOwl:id>
```

Now perhaps all of these IDs are in CURIE format, so this is not very informative? But I'm left wondering what the distinction between DOID (namespace in pattern) and MONDO/EFO (namespace not in pattern). In my experience, they are all similar in that they are always provided with the prefix and never in bare form.

**Comment by bgyori** [comment]
Yes, I meant e.g., identifiers.org, you can see the difference in the ID patterns, 

![image](https://user-images.githubusercontent.com/5939016/135352011-84b676dd-f15c-4f80-8092-c76373589503.png)
vs
![image](https://user-images.githubusercontent.com/5939016/135352065-df30edf4-1e64-48a0-8aa2-acd1e9cc8c70.png)

In terms of the OWL, EFO: is likely there explicitly because the EFO ontology contains elements from other ontologies like BFO. However, for consistency, one might expect to see DOID:DOID:7551 since DO IDs are supposed to have the namespace embedded...

**Comment by dhimmel** [comment]
> Yes, I meant e.g., identifiers.org, you can see the difference in the ID patterns,

I am entertaining the possibility that identifiers.org (and the other registries) are wrong. Although perhaps they are so authoritative that their wrongs become future rights... and that it would be a mistake to deviate. Although I see bioregistry does deviate when identifiers.org sometimes, like adding ICD revisions (e.g. `icd9`).

@matentzn with someone involved in MONDO, is the `MONDO:` prefix part of the local identifier? @zoependlington, how about for EFO?

> However, for consistency, one might expect to see DOID:DOID:7551 since DO IDs are supposed to have the namespace embedded...

I thought the whole purpose of the "Namespace in Pattern" field is such that you can just do `id` for the CURIE rather than `prefix:id`. Because `DOID:DOID:7551` is something bad that we want to avoid? Although perhaps it is not bad, just that you never see it in the wild, like in ontology xrefs.

**Comment by matentzn** [comment]
I think this question raises an important issue about the naming of "things" in the process of dealing with prefixes, curies, IDS, URI namespace prefixes, local IDs etc etc. No one would ever refer to 0000001 to denote "Disease or Disorder", but I would still say that its is somehow the "local ID". - Once @cthoyt has a PR ready for the glossary, I will give more details.

**Comment by cthoyt** [comment]
I will return with a (hopefully) satisfying answer later today. Short version is that in OBO world, they consider entire CURIEs as local identifiers in the OBO namespace, and this nonsense has propagated far and wide, causing chaos and confusion for everyone (even reaching outside of the OBO Foundry to the EFO)

**Comment by matentzn** [comment]
Dont forget that by far the majority of the tools use something even worse, which is called `short_form` (add to glossary). For example, instead of using MONDO:0000001 (CURIE), they use `MONDO_0000001` (short form). Tough! But we need facilities like regex checking to avoid this, to avoid `MONDO:MONDO_0000001` croping up in our databases.

**Comment by cthoyt** [comment]
Btw one of the other main reasons for confusion is a lot of people just write `identifiers` when they mean CURIEs, not local identifiers. So if you live in a world when someone has a column that's called ID and you see EFO:123457 in it, it means this column has a CURIE in it, and is just confusingly named

**Comment by matentzn** [comment]
There is a technical difference between short_form and curie as well. Short-form is usually used to denote the remainder of a URL after the URL namespace has been cut off; So while `MONDO_0000001` is the shortform for http://purl.obolibrary.org/obo/MONDO_0000001, `license` is the short form of http://purl.org/dc/terms/license. Its basically not anything - its a construct that was used for convenience by simply meaning: the "last part of the path or the URL". The only reason to mention it is to explicitly forbid its being used anywhere.

**Comment by bgyori** [comment]
I'm not sure that there should be pressure to "right some kind of wrong". At the end of the day, the key is for there to be a machine-readable standard shared by a large number of systems. From the perspective of software systems the style of identifiers really doesn't matter as long as there is a formal pattern that can be validated against. Most systems have taken the MIRIAM standard as reference (at least for prefixes covered there) and I believe it's difficult and disruptive to abandon that (obviously, Bioregistry significantly expands on the space of prefixes and fixes obvious mistakes but a stylistic change in the standard is not the same thing). I can certainly say that it would be a major effort and disruption to change identifier patterns in running code and persisted artifacts in the systems that I've developed, and at the end of the day there would be zero value created by the whole exercise.

**Comment by cthoyt** [comment]
Thanks everyone for all of the great discussion. The ultimate decision was to address this with #213 where all of the regular expressions with redundant namespace information in the pattern in MIRIAM were overridden, and utility functions were renamed to better represent that the bioregistry is specifically interested in LUIs
