### ISSUE TITLE
Add data model for providers

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#196]
In case there are arbitrary extra providers for a given prefix, it makes sense to allow curation of these. Taking inspiration from Identifiers.org and N2T, they can have a locally unique code (i.e., for the given prefix), a format string, and some extra metadata (tbd)

**Comment by egonw** [comment]
> In case there are arbitrary extra providers for a given prefix

Ah, sorry, I assumed it already did that. This is extremely common, I think.
