### ISSUE TITLE
Update regular expression pattern for `interpro` because failed on `IPR016380`

### ISSUE THREAD

**Issue by bgyori** [biopragmatics/bioregistry#226]
There seems to be some kind of a problem here, since the example ID seemingly matches the pattern but cannot be resolved.
![image](https://user-images.githubusercontent.com/5939016/139365060-663ad76c-000c-42eb-9a88-fe0a55d7b7c4.png)

Further, the identifiers.org link for this entry appears as https://identifiers.org/IPR:IPR016380 but it should actually be https://identifiers.org/interpro:IPR016380.

I also noticed the `interpro` entry is marked as deprecated, is that on purpose?

**Comment by cthoyt** [comment]
I made a few updates in 3225447  to solve this issue:

1. Identified a bug in the code that calls whether a resource is deprecated (only allowed you to explicitly state True, but not false)
2. Explicitly overrode the InterPro entry's deprecated status to be false
3. Removed a duplicate prefix "ipr" that was corresponding to duplicate entries for interpro in prefixcommons
