### ISSUE TITLE
Better documentation of the registry data files

### ISSUE THREAD

**Issue by dhimmel** [biopragmatics/bioregistry#232]
From the [readme](https://github.com/biopragmatics/bioregistry/blob/e75275160e6b6ffd619e83579bbc629e3d0309f6/README.md#-download):

> The underlying data of the Bioregistry can be downloaded directly
from [here](https://github.com/biopragmatics/bioregistry/blob/main/src/bioregistry/data/bioregistry.json).
Several exports to YAML, TSV, and RDF can be downloaded via https://bioregistry.io/download.

Looking through the repo, I see the following two locations for data:
 
- `src/bioregistry/data` presumably for input data
- `docs/_data` presumably for output data (generated by CI)

But I don't see any docs for these files, such as a README file.

In https://github.com/manubot/manubot/issues/305, @cthoyt pointed me to `docs/_data/registry.tsv` which contains what I want: the actual bioregistry metadata fields after merging all the input registries (i.e. the resolved/consensus view). But `docs/_data/registry.yaml` seems not to contain all the output fields (despite having the same file stem name).

This issue has two parts:

1. better documentation of the data, especially the output files
2. based on 1, a request to create a JSON/YAML format of the consensus view available in `docs/_data/registry.tsv`

**Comment by bgyori** [comment]
I agree, we should work on these, thanks!

**Comment by cthoyt** [comment]
[Consensus JSON](https://github.com/biopragmatics/bioregistry/blob/main/exports/registry/registry.json) and [consensus YAML](https://github.com/biopragmatics/bioregistry/blob/main/exports/registry/registry.yml) files are available as of #235 along with some nice documentation updates. #236 will update the documentation of the internal data then we can see if we've addressed all of @dhimmel's concerns

**Comment by cthoyt** [comment]
Sorry for the double message but I wanted to get this all cleaned up and merged. If there's any feedback or follow-up that you think we should do after #235 and #236, please let us know :)

**Comment by dhimmel** [comment]
Fantastic! Changes look great and much clearer now what data is where. Looking forward to using `exports/registry/registry.json`.
