### ISSUE TITLE
Deterministic registry.json export 

### ISSUE THREAD

**Issue by dhimmel** [biopragmatics/bioregistry#246]
It looks like the order of elements of resource `synonyms` in `exports/registry/registry.json` is non-deterministic. See for example the diff in https://github.com/biopragmatics/bioregistry/commit/972c73f26a54f24b5ba32801741c772b1f5b6ddb#diff-e8b207c286b5c42be55c1819fc94eac2678719bd662a78e1ae454fd00a39ec59

![image](https://user-images.githubusercontent.com/1117703/140617820-e5cdf3bb-510d-479f-9e4a-fc59f4706758.png)

Would be nice for the git diff to only include actual changes.

Unrelated: can considering ordering output fields by the pedantic model rather than sorting them alphabetically.

**Comment by cthoyt** [comment]
This was solved in f9e4140b6829a50690886b2afe5eceb8761970b2, sorry I forgot to link them
