### ISSUE TITLE
Update regular expression pattern for uspto (US Patent Numbers)

### ISSUE THREAD

**Issue by dhimmel** [biopragmatics/bioregistry#253]
### Prefix

uspto

### New Regular Expression Pattern

`^(\d{1,2},?\d{3},?\d{3}|(PP|RE|AI|RX)\d{2},?\d{3}|(D|T|H|X)\d{3},?\d{3})$`

### Explanation

Currently the regex for the [uspto](https://bioregistry.io/registry/uspto) prefix is `^(D|PP|R|T|H|X|AI)?\d+$`. I think we might be able to restrict the pattern a bit more based on the poorly-written information at https://patft.uspto.gov/netahtml/PTO/srchnum.htm:

> Utility patents must have numbers entered as seven or eight characters in length, excluding commas, which are optional. 
> Examples:
> 10,000,000 -- 100000000 -- 6923014 -- 6,923,014 -- 0000001
> Note: Utility Patent 10,000,000 will issue in 2018
>
> The below patent types must have numbers entered as seven characters in length, excluding commas, which are optional. 
> Examples:
>
> Design --	D339,456 D321987 D000152
> Plant --	PP08,901 PP07514 PP00003
> Reissue --	RE35,312 RE12345 RE00007
> Defensive Publication --	T109,201 T855019 T100001
> Statutory Invention Registration --	H001,523 H001234 H000001
> Additional Improvement --	AI00,002 AI000318 AI00007
> X-Patents --	X011,280 X007640 X000001
> Reissued X-Patents --	RX00116 RX00031 RX00001

I crafted a regex at https://regex101.com/r/tPlzw7/1 and noticed that two of the examples (`100000000` & `AI000318`) don't actually match the description.

Before merging we should:

- check all existing patent numbers to make sure they match this regex
- determine whether a more restrictive but more complex / less readable patterns are preferred for the bioregistry

### Contributor ORCID

0000-0002-3012-7446

**Comment by dhimmel** [comment]
# Exceptions

Will edit this post will corner cases I come across

There is a patent from 1880 with patent number `234614`. When I search it on the USPTO search, it [resolves](https://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO1&Sect2=HITOFF&d=PALL&p=1&u=%2Fnetahtml%2FPTO%2Fsrchnum.htm&r=1&f=G&l=50&s1=0234614.PN.&OS=PN/0234614&RS=PN/0234614) but adds a `0` prefix to become 7 digits.

**Comment by dhimmel** [comment]
There's also [this page](https://www.uspto.gov/patents/apply/applying-online/patent-number) with slightly different information.

> A **Patent Number** is assigned by the USPTO. A patent number may include up to eight characters and is formatted as follows:
> -   **Utility** : Patent numbers consist of six, seven or eight digits. Enter the Patent number excluding commas and spaces and omit leading zeroes.
> -   **Reissue** : (e.g., Rennnnnn, RE000126) must enter leading zeroes between "RE" and number to create 6 digits.
> -   **Plant Patents** :(e.g., PPnnnnnn, PP000126) must enter leading zeroes between "PP" and number to create 6 digits.
> -   **Design** : (e.g., Dnnnnnnn, D0000126) must enter leading zeroes between "D" and number to create 7 digits.
> -   **Additions of Improvements** : (e.g., **AInnnnnn** , AI000126AI) must enter leading zeroes between "AI" and number tocreate 6 digits.
> -   **X Patents** : (e.g., **Xnnnnnnn** , X0000001) must enter leading zeroes between "X" and number to create 7 digits.
> -   **H Documents** : (e.g., **Hnnnnnnn** , H0000001) must enter leading zeroes between "H" and number to create 7 digits.
> -   **T Documents** : (e.g., **Tnnnnnnn** , T0000001) must enter leading zeroes between "T" and number to create 7 digits.

**Comment by cthoyt** [comment]
Hey Daniel, thanks for looking back into this. At the moment, the Bioregistry *de facto* adopted the style from Identifiers.org, which was not to over-specify the regular expressions, but that may well have come from the difficulty of writing complex, correct ones. I think for the Bioregistry, as long as we're not getting too many false negatives, I'm not against making regular expressions more specific.

However, it looks like the situation here is pretty far outside of the norm. One alternative could be to consider subspacing (see #133) as a way to break this up into several specific entries with less complex regexes, then have a top-level, more general prefix (though this kind of proliferation of prefixes has its own associated issues). I'm not a huge fan of this idea since it just diffuses the complicatedness

**Comment by cthoyt** [comment]
How many patents are there? It's not possible to download the whole dump, right?  I built this repo (https://github.com/bioregistry/regex-report) to periodically check how good the regexes actually are, but obviously this is limited to resources where I can download some artifact that lists all identifiers.

**Comment by dhimmel** [comment]
Some helpful context is that I know little about patents and opened this issue as a public forum for creating a USPTO identifier regex. Will probably require someone more knowledgeable to find this issue and contribute before we can do anything. But I'll keep posting my notes.

> download the whole dump

There's bulk data available at https://bulkdata.uspto.gov/. Another option would be to use [Google Patents](https://github.com/google/patents-public-data). If we find bulk lists of patent numbers here, it's probably worth adding them to the regex-report repo (does regex-report import the actual identifiers [from pyobo](https://github.com/bioregistry/regex-report/blob/28115ec80d74d9a3b975c2e611551ef5ec0b6594/build.py#L90), so actually pyobo would be where we add the patent IDs?)

Another complication is that there appear to be USPTO IDs for both:

- Issued patents (patent grants)
- Published patent applications (pre-grant publications)

And I'm not sure whether the `uspto` should/does cover both identifier types.
