### ISSUE TITLE
Discussion about European Community Number

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#257]
Information:
- https://en.wikipedia.org/wiki/European_Community_number
- https://dodona.ugent.be/en/courses/12/series/102/activities/1807617945/#

Pattern: `^\d{3}-\d{3}-\d$`
Example: `200-003-9` for dexamethasone

The [European Chemicals Agency website](https://echa.europa.eu/information-on-chemicals) allows you to search by European Community Number, but then it redirects to pages that do not actually use the EC number in their URL like https://echa.europa.eu/substance-information/-/substanceinfo/100.000.004

**Comment by cthoyt** [comment]
Found wikidata property for this! https://www.wikidata.org/wiki/Property:P232

**Comment by bgyori** [comment]
Looking at this prefix right now related to an application and I can't figure out if there is a resolver for EC numbers, and meanwhile, can't figure out what the identifiers like [100.000.004](https://echa.europa.eu/substance-information/-/substanceinfo/100.000.004) stand for... Does anyone know what these latter numbers are?
