### ISSUE TITLE
Add prefix [FYECO]

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#268]
### Prefix

fyeco

### Name

Fission Yeast Experimental Conditions Ontology

### Homepage

https://github.com/pombase/fypo

### Description

PomBase manages gene and phenotype data related to Fission Yeast. FYECO contains experimental conditions relevant to fission yeast biology. The FYECO namespace shows up in data ingests from PomBase.

### Example Local Unique Identifier

0000003

### Regular Expression Pattern for Local Unique Identifier

^\d{7}$

### Redundant Prefix in Regular Expression Pattern

FYECO:

### URI Format String

http://purl.obolibrary.org/obo/FYECO_

### Contributor Name

Val Wood

### Contributor ORCiD

0000-0001-6330-7526

### Additional Comments

Rather than admitting FYECO to the OBO foundry, we secure the prefix here at bioregistry. The FYECO namespace shows up in a lot of ingests (basically anywhere you ingest PomBase gene-phenotype data). Future work includes mapping FYECO to other OBO ontologies, but this is way ahead in the future. cc @ValWood

**Comment by cthoyt** [comment]
@matentzn I'm not a big fan of using the Bioregistry to resolve to another resolver, I'd prefer to curate the actual URI format string in the Bioregistry. Can you point me to the right place?

Here is an excellent example because FYECO isn't actually registered in the OBO PURL system as far as I can tell.

**Comment by matentzn** [comment]
There is no URI resolver for FYECO - they wanted to use OBO foundry, but FYECO really should not be in OBO library. The problem is that OBO format _itself_ maps to OBO Foundry purls; so their IRIs will map to that by default. How else will we deal with this issue?

**Comment by cthoyt** [comment]
Bioregistry doesn't require URI formats, so I think it's better to omit it than put something misleading for FYECO

At some point the Bioregistry could directly ingest the OBO PURL configuration to resolve all of these internally, too.

**Comment by matentzn** [comment]
Ok great!

Just remove the URI mapping then!

**Comment by cthoyt** [comment]
The other thing that I don't agree with is that you added Val's information on the contribution - this is actually supposed to refer to Nico's contribution to the bioregisry, not the contact information for the resource. However, I can see how that's confusing, and probably deserves an improvement to the template itself!

**Comment by matentzn** [comment]
I just copied the information provided by @ValWood, that's all. I didn't actually do anything aside from copy paste, so I think the credit should go to her!

**Comment by cthoyt** [comment]
Fair enough :)

**Comment by ValWood** [comment]
Thanks both.
val
