### ISSUE TITLE
Error in mapping file for PECO

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#272]
https://github.com/biopragmatics/bioregistry/blob/main/exports/sssom/bioregistry.sssom.tsv

subject_id | predicate_id | object_ud | match_type
-- | -- | -- | --
bioregistry:peco | skos:exactMatch | bioportal:PECO | sssom:HumanCurated
bioregistry:peco  | bioregistry:peco | skos:exactMatch | obofoundry:EO | sssom:HumanCurated
bioregistry:peco  | bioregistry:peco | skos:exactMatch | ols:peco | sssom:HumanCurated
bioregistry:peco  | bioregistry:peco | skos:exactMatch | ontobee:PECO | sssom:HumanCurated
bioregistry:peco  | bioregistry:peco | skos:exactMatch | prefixcommons:PECO | sssom:HumanCurated

The OBO CURIE should in fact be obofoundry:PECO

https://obofoundry.org/ontology/peco

I suspect some confusion caused by the fact that some time ago EO became PECO:

https://obofoundry.org/ontology/eo

There is an argument for including obo:EO as a non-exact match for PECO (and for obsoleted ontologies more generally), but the exact match should be to PECO

**Comment by cthoyt** [comment]
I could not figure out what the difference between EO and PECO are from the information available in the OBO Foundry and outwards. So they should be treated as two separate things?

I also don't know how much (if any) metadata is pulled into the bioregistry about replacements. That might be a bit of scope creep
