### ISSUE TITLE
obofoundry metaregistry pages shows incorrect example purl

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#275]
Yes, I won't shut up about case sensitivity... it will be inscribed on my gravestone... all in lowercase

But this is different from #46 which is resolved

https://bioregistry.io/metaregistry/obofoundry

Example CURIE
chebi:24867

Example CURIE Link
http://purl.obolibrary.org/obo/chebi_24867

Both the CURIE and the PURL should be all uppercase.

**Comment by cthoyt** [comment]
This an excellent corner case. The issue is that the obo foundry when acting as a provider doesn’t accept uppercase nor mixed case prefixes like in https://obofoundry.org/ontology/CHEBi

**Comment by cthoyt** [comment]
At least the first actionable thing is we should be able to fix the link generation

**Comment by cmungall** [comment]
In the short term, I would rather the CURIEs were correct and the link to OBO informational pages broken

I filed an issue to make the OBO pages case insensitive but I am not sure we will get to this soon:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1728
