### ISSUE TITLE
Use SHACL vocabulary in RDF

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#305]
[SHACL](https://www.w3.org/TR/shacl/) is a controlled vocabulary that has the facility for describing the structure of RDF itself.

The OBO Foundry has demonstrated it's useful to represent a prefix map using SHACL. Their implementation that converts the OBO Foundry's prefix map into SHACL is here https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/util/make-shacl-prefixes.py

It would be useful to create a similar export of the Bioregistry. This could be implemented in this file: https://github.com/biopragmatics/bioregistry/blob/main/src/bioregistry/export/prefix_maps.py next to the code that generates JSON-LD-style prefix maps.

**Comment by cmungall** [comment]
Yes, we use this for OBO as well: http://purl.obolibrary.org/meta/obo_prefixes.ttl

**Comment by cthoyt** [comment]
@cmungall this is where I got the idea ;)

**Comment by cthoyt** [comment]
@kkaris do you want to take care of this?

**Comment by kkaris** [comment]
Will do!
