### ISSUE TITLE
pav prefix has strange ideosyncractic prefix resolution

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#306]
Check http://bioregistry.io/registry/pav

When getting a context, I expect

```
pav: http://purl.org/pav/
```

instead, I get

```
pav: https://pav-ontology.github.io/pav/index.html#http://purl.org/pav/
```

http://purl.org/pav/authoredBy, the official IRI, redirects to an RDF dump of PAV (should have used content negotiation).

For the sssom context, i need:

```
pav: http://purl.org/pav/
```

Would that be possible?

**Comment by cthoyt** [comment]
Yes, this sounds like a simple proposal of changing the `uri_format` attribute of PAV's entry. I can take care of this for you

**Comment by matentzn** [comment]
Thank you!
