### ISSUE TITLE
Should "dc:" prefix default to elements or terms?

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#307]
I am generally using `dce` for elements, and `dcterms` for terms, but its not clear to me how to decide whether the one or the other is preferable for `dc`

- http://purl.org/dc/terms/
- http://purl.org/dc/elements/1.1/

Bioregistry suggests element. DC itself tries to promote terms.. Whats you stance on that @cthoyt?

**Comment by cthoyt** [comment]
Does this mean we should consider DC and DCTERMS as the same prefix? Like should we merge these?

**Comment by matentzn** [comment]
hm... I dont know what that means exactly, in my opinion they are the same, but they should be allowed to co-exist in large, non-harmonised projects.. Not sure. I think I prefer both of these to appear in my context? Not sure though.

**Comment by cthoyt** [comment]
needs a new issue for discussion, it won't block merging these other updates (I think?)

**Comment by matentzn** [comment]
Yeah, I think so too.
