### ISSUE TITLE
Can not resolve when identifier has slash

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#31]
https://bioregistry.io/doi:10.1038/nbt1156 fails to resolve since Flask is probably thinking the slash is special. Need to update the flask routing to solve this one.

**Comment by cthoyt** [comment]
This has been solved around https://github.com/bioregistry/bioregistry/commit/e85455b7311291f23eaa31fc677881accf44e73c

**Comment by kkaris** [comment]
I believe this is still/again an issue: look at e.g. the registry page for [CTRI](https://bioregistry.io/registry/ctri) (India Clinical Trials Registry), and click on the example CURIE: https://bioregistry.io/reference/ctri:CTRI/2023/04/052053, at least for me I get an internal server error.

**Comment by cthoyt** [comment]
check https://bioregistry.io/ctri:CTRI/2023/04/052053 - this is just a 404 because there's no resolution. I know how to solve the reference/ endpoint issue the same way it's solved for the resolve endpoint
