### ISSUE TITLE
Zoonomia prefix request

### ISSUE THREAD

**Issue by diekhans** [biopragmatics/bioregistry#314]
### Prefix

znm

### Name

Zoonomia Project

### Homepage

https://zoonomiaproject.org/

### Description

The Zoonomia Project is an international collaboration to discover the genomic basis of shared and specialized traits in mammals

### Example Local Unique Identifier

000000001.1

### Regular Expression Pattern for Local Unique Identifier

^[0-9]+\.[0-9]+$

### Contributor Name

Mark Diekhans

### Contributor ORCiD

0000-0002-0430-0989

### Contributor GitHub

diekhans

**Comment by cthoyt** [comment]
Hi @diekhans can you please provide a web page that lets you resolve the example identifier?

**Comment by cthoyt** [comment]
@diekhans It's fine if your prefix doesn't have a resolver - there are plenty of entries in the Bioregistry that are lacking that. However, most of these were motivated by their ubiquitous use in other resources. Maybe you can provide some context by showing an example of where I might find a ZNM identifier being used - I'm not sure it would be smart to accept a new prefix into the Bioregistry that we can't show a usage of (this could lead to people parking certain prefixes).

I'd point to https://github.com/sorgerlab/famplex as an example of a controlled vocabulary that my group developed, then we used GitHub Pages to generate a page for each entry that we were able to put in the https://bioregistry.io/registry/fplx entry in the Bioregistry. It generates static pages that GitHub hosts for free - perfect for a small vocabulary that won't change often. Even better is to use CI/CD to automatically rebuild the site on any change to the underlying JSON or TSV.

**Comment by diekhans** [comment]
Nice idea.  We are working on the github repo, so it isn't ready
yet.  Lets just wait until that is up to merge.

We were not planning to have the reconstruct genomes in
individual FASTA files, as they are contained in a larger,
HDF5-based file.  However we could revisit that, it is only disk
space, and then we could provide URLs.

**Comment by cthoyt** [comment]
My suggestion is to prepare your controlled vocabulary and other metadata associated with each term (e.g., labels, synonyms, relationships) completely independent from the data files. You could follow some ideas from this blog post https://cthoyt.com/2020/05/12/building-an-ontology.html or if you want to go down the OWL route I could dig up some references to the OBO community's resources for you

**Comment by diekhans** [comment]
The current data will not have an ontology or controlled
vocabulary, just fasta files.  We might need to as the project
evolves.

I have friends in the ontology world, so no shortage of
resources (Melissa Haendel sent me here).  However, the blog
looks well worth a read!

Despite being conceptually clear, the barrier to entry to using
ontologies is higher than is desired  for us genomicists.

thanks, we will be back.

**Comment by cthoyt** [comment]
Great! One last question - can you link me to a download for one of these FASTA files?

**Comment by cthoyt** [comment]
@diekhans do you have any updates on this?

**Comment by diekhans** [comment]
This is stuck behind other more urgent tasks on the project,
but has not been forgotten.

**Comment by cthoyt** [comment]
Hi @diekhans, I hope you're having a nice fall. We can try and finish up this new prefix request if you're able to point me to an example of where one of these identifiers is used. Thanks :)

**Comment by cthoyt** [comment]
Hi @diekhans, I'm going to close this issue for now. Please feel free to re-open it when you've got something to point us to.
