### ISSUE TITLE
Title correction Biosapiens Protein Feature Ontology

### ISSUE THREAD

**Issue by MinRo60** [biopragmatics/bioregistry#349]
### Prefix

bs

### Explanation

Wrong title Biosapiens Protein Feature Ontology the correct tile is The Sequence Ontology

### Contributor ORCID

0000-0002-6240-9325

**Comment by cthoyt** [comment]
Note that this prefix corresponds to terms that are disjoint from the sequence ontology that are in https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/Ontology_Files/subsets/biosapiens.obo. While this also lives in the sequence ontology world, it's not the same. Perhaps a good next step you could take is to get in touch with some SO people and see if they can update this OBO to make it more clear what the title should be, if something different from Biosapiens Protein Feature Ontology
