### ISSUE TITLE
Add prefix [omim.ps]

### ISSUE THREAD

**Issue by sierra-moxon** [biopragmatics/bioregistry#354]
### Prefix

omim.ps

### Name

Online Mendelian Inheritance in Man

### Homepage

https://www.omim.org/

### Description

OMIM is a comprehensive, authoritative compendium of human genes and genetic phenotypes that is freely available and updated daily. OMIM contains phenotypic series information (identifiers and URIs) separate from their main resource.

### Example Local Unique Identifier

PS603933

### Regular Expression Pattern for Local Unique Identifier

^\d+$

### Redundant Prefix in Regular Expression Pattern

PS

### URI Format String

https://www.omim.org/phenotypicSeries/$1

### Contributor Name

Sierra Moxon

### Contributor ORCiD

0000-0002-8719-7760

**Comment by cthoyt** [comment]
This already exists at https://bioregistry.io/registry/mim.ps. I tried to keep compatibility with Identifiers.org since it calls OMOM `mim`, but maybe it's time to throw that choice away
