### ISSUE TITLE
Add prefix [cpt]

### ISSUE THREAD

**Issue by sierra-moxon** [biopragmatics/bioregistry#357]
### Prefix

cpt

### Name

Current Procedural Terminology

### Homepage

https://www.aapc.com/

### Description

Current Procedural Terminology, more commonly known as CPT®, refers to a medical code set created and maintained by the American Medical Association — and used by physicians, allied health professionals, nonphysician practitioners, hospitals, outpatient facilities, and laboratories to represent the services and procedures they perform. No provider of outpatient services gets paid without reporting the proper CPT® codes. [taken from this site](https://www.aapc.com/codes/cpt-codes-range/)]

### Example Local Unique Identifier

00103

### Regular Expression Pattern for Local Unique Identifier

^[0-9]+$

### URI Format String

https://www.aapc.com/codes/cpt-codes/$1

### Contributor Name

Sierra Moxon

### Contributor ORCiD

0000-0002-8719-7760

### Additional Comments

Additional contributor - Colleen Xu (0000-0003-2975-882X)

[requested via Biolink Model](https://github.com/biolink/biolink-model/pull/993)

**Comment by cthoyt** [comment]
Thanks @sierra-moxon @colleenXu! This will appear on the website on the nightly build unless you need it ASAP today in which case I can trigger a new deploy
