### ISSUE TITLE
TIGRfams do not resolve - use NCBI CDD as resolver instead

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#366]
The TIGRfam entries don't resolve - I don't think the JCVI site is supported any more

the NCBI CDD service will however resolve these:

https://www.ncbi.nlm.nih.gov/cdd?term=TIGR00010

In fact the TIGRfams moved ownership to NCBI:

https://ftp.ncbi.nlm.nih.gov/hmm/TIGRFAMs/license_and_availability.txt

cc @danielhhaft 

So I think the NCBI URL should be considered *canonical*

@kltm we may want to update the reusable data entry:

https://reusabledata.org/tigrfams

If NCBI is now the custodian, I am not sure this entry is still accurate. I would relabel the current one jcvi_tigrfams or something.

The new license (CC-SA) is hopefully clearer (though regrettably still more restrictive than IMO it should be)

**Comment by cthoyt** [comment]
Thanks for the suggestion @cmungall. Not sure if the other parts of this issue are actionable in the Bioregistry, but feel free to continue to use this issue as a forum for discussion 😃
