### ISSUE TITLE
Relax eccode regex to allow for provisional IDs

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#376]
Currently the regex is `^\d{1,2}(\.\d{0,3}){0,3}$`

Example: https://enzyme.expasy.org/EC/1.14.11.n2

Relax to `^\d{1,2}(\.n{0,1}\d{0,3}){0,3}$`

(this may be too relaxed if the n only occurs at level 4?)

These are valid resolvable identifiers that are linked from authoritative resources like GO, Rhea

See also

- https://github.com/geneontology/go-ontology/issues/23312

**Comment by cthoyt** [comment]
I think the n only occurs at level 4

**Comment by cthoyt** [comment]
btw some of these "provisional" identifiers are several years old

**Comment by cmungall** [comment]
yep, I believe there are known backlogs here...

**Comment by cthoyt** [comment]
Maintain the database on GitHub in a TSV file! Viva la revolución!

will send a fix for the regex momentarily
