### ISSUE TITLE
provide a JSON-LD 1.1. context of the registry

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#380]
Not this:

https://raw.githubusercontent.com/biopragmatics/bioregistry/main/exports/rdf/bioregistry.jsonld

Something that includes this:

http://purl.obolibrary.org/meta/obo_context.jsonld

see https://github.com/prefixcommons/biocontext

**Comment by cthoyt** [comment]
You found a full export of the RDF dump in JSON LD, but slightly to the side is what you're looking for. See the listing in https://github.com/biopragmatics/bioregistry/tree/main/exports/contexts, where you can get what you want in JSONLD (https://github.com/biopragmatics/bioregistry/blob/main/exports/contexts/bioregistry.context.jsonld) and also SHACL (https://github.com/biopragmatics/bioregistry/blob/main/exports/contexts/bioregistry.context.ttl)
