### ISSUE TITLE
Link to review team is 404

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#381]
On https://github.com/biopragmatics/bioregistry/blob/main/docs/GOVERNANCE.md

links to https://github.com/orgs/biopragmatics/teams/bioregistry-reviewers

Maybe it's set as a private team, presumably accidentally?

**Comment by cthoyt** [comment]
I tried very hard to make this public, but it appears teams are not a public feature :(

**Comment by cthoyt** [comment]
So this governance document outlines that this should be updated on change to the team, so the action item is to add a note that says this team can't be viewed publicly as a limitation of Github
