### ISSUE TITLE
[new prefixes] add more taxonomic resources

### ISSUE THREAD

**Issue by Adafede** [biopragmatics/bioregistry#396]
As discussed,

I am opening an issue to improve the coverage of the Bioregistry for taxonomic databases prefixes.

A good starting point would be:

https://www.wikidata.org/wiki/Wikidata:WikiProject_Taxonomy#Databases

@cthoyt There are many, if you need a priority list, I could start by doing a ranked list dependent on the number of items with taxonomic DB identifiers on Wikidata.

A huge advantage is that for each listed DB, the related property has already the formatted URL described, etc. See https://www.wikidata.org/wiki/Property_talk:P9157 for an example.

Happy to elaborate and help where I can!

**Comment by cthoyt** [comment]
wooooow so many. this is great though, since wikidata already has a lot of information that would be useful. Tbh i would love to curate the whole bioregistry on wikidata but there's the issue that it needs properties, and there's a high contributor burden to get them to assign them

**Comment by cthoyt** [comment]
are these all sub-properties of a specific property so we could make a SPARQL query to get the whole list of them? I think we can write a custom script to populate the bioregistry with all of these and then do some manual curation for anything else we need that's not available in wikidata (but that might not be anything if we're lucky)

**Comment by Adafede** [comment]
Sadly, I think the mapping of the property constraints among them are not consistent... @Daniel-Mietchen  might help on this!

**Comment by cthoyt** [comment]
Then we can just scrape this page to get the list of properties
