### ISSUE TITLE
Add prefix nifstd

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#402]
### Prefix

nifstd

### Name

NIF Standard ontology

### Homepage

https://github.com/SciCrunch/NIF-Ontology

### Description

NIFSTD is a neuroscience ontology that maintains an extensive set of terms and concepts important for the domains of neuroscience and biology.

### Example Local Unique Identifier

nifext_55

### Redundant Prefix in Regular Expression Pattern

NIFSTD

### URI Format String

http://uri.neuinfo.org/nif/nifstd/

### Contributor Name

Nicolas Matentzoglu

### Contributor ORCiD

0000-0002-7356-1779

**Comment by cthoyt** [comment]
@matentzn I was actually hoping you'd add the NIFEXT, since that's a "real" prefix and this one is more meta, I'd rather exclude it completely if its contents can all have their own instead.

**Comment by matentzn** [comment]
Oh maybe you are right:

https://raw.githubusercontent.com/SciCrunch/NIF-Ontology/master/ttl/generated/NIFSTD-ILX-mapping.ttl

Check the prefixes. But seems we need to add them all then?

**Comment by cthoyt** [comment]
I am happy to add them all if we can give really good descriptions of each that explain why they exist and when to use each

**Comment by matentzn** [comment]
Let close this for now in favour of #404
