### ISSUE TITLE
Update regular expression pattern for google.patent

### ISSUE THREAD

**Issue by bgyori** [biopragmatics/bioregistry#408]
### Prefix

google.patent

### New Regular Expression Pattern

^[A-Z]{2,4}\d+([A-Z])?([0-9])?$

### Explanation

The old pattern doesn't capture all patent numbers. See e.g., https://patents.google.com/patent/USRE38117E1. The new pattern matches all examples in a set of ~65k patent numbers I am looking at.

### Contributor ORCID

0000-0001-9439-5346

**Comment by cthoyt** [comment]
@bgyori can you give some examples of different identifiers that the old regular expression didn't match so i can add them to the examples list? Each example is checked that it passes the regular expression.

See also https://github.com/biopragmatics/bioregistry/issues/253, which was about USPTO but I think they are related.

**Comment by bgyori** [comment]
The example I gave above exercises all the changes proposed in the pattern change. As for relationships with USPTO, that leads to a more complicated question of whether these patterns aim to be provider-specific, and thus the pattern for `google.patent` and `uspto` need to be kept in sync, or whether we imagine a set of universal properties that patents have and impose that on all providers that serve patent information. One difference between this proposal and #253 is that here I actually need to extend the pattern to accept valid patent IDs whereas that PR aims to make the pattern more restrictive.
