### ISSUE TITLE
Fix Plant Ontology URI format

### ISSUE THREAD

**Issue by Adafede** [biopragmatics/bioregistry#424]
### Prefix

po

### Explanation

I think it should be 
`https://browser.planteome.org/amigo/term/PO:$1` 

instead of

`http://www.plantontology.org/amigo/go.cgi?view=details&query=PO:$1`

The same applies to the homepage. (http://www.planteome.org/ instead of http://www.plantontology.org/)

### Contributor ORCID

0000-0003-0443-9902

**Comment by cthoyt** [comment]
Both seem to work. Using `PO:0009089` as a concrete example:

1. http://www.plantontology.org/amigo/go.cgi?view=details&query=PO:0009089
2. https://browser.planteome.org/amigo/term/PO:0009089

I like the more modern one as the default, though

**Comment by Adafede** [comment]
Hmmm...

First one is exactly the same as https://planteome.org/?view=details for me?

**Comment by Adafede** [comment]
Yes, indeed, exactly the same one as http://www.plantontology.org/amigo/go.cgi?view=details&query=PO:0009089 for me.

<img width="1680" alt="Capture d’écran 2022-06-15 à 10 38 42" src="https://user-images.githubusercontent.com/44283913/173783091-82fff680-0893-49d1-8d24-23c117e84066.png">
<img width="1680" alt="Capture d’écran 2022-06-15 à 10 38 53" src="https://user-images.githubusercontent.com/44283913/173783101-cee52713-ff83-416a-8246-4e39b20c301d.png">
