### ISSUE TITLE
update description for ncats.drug

### ISSUE THREAD

**Issue by sierra-moxon** [biopragmatics/bioregistry#444]
### Prefix

ncats.drug

### Explanation

It looks like part of the description for this resource got truncated.  I think we should replace the description with this:

"The National Center for Advancing Translational Sciences](http://www.ncats.nih.gov/) (NCATS) has developed Inxight Drugs as a comprehensive portal for drug development information. NCATS Inxight Drugs contains information on ingredients in medicinal products, including:

- US Approved Drugs
- Marketed Drugs
- Investigational Drugs
- Other Substances"

### Contributor ORCID

0000-0002-8719-7760

**Comment by cthoyt** [comment]
All fixed! Thanks for point this out :)
