### ISSUE TITLE
regex for PR is too restrictive

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#45]
http://bioregistry.io/registry/pr

```
Pattern
^PR:P?\d+$
```

there are in fact PR:Onnnns...

**Comment by cmungall** [comment]
also isoforms, e.g. PR:Pnnnnn-N

**Comment by cthoyt** [comment]
I made a regular expression report at https://bioregistry.github.io/regex-report/ so we can streamline fixing some regexes

**Comment by cthoyt** [comment]
This was addressed in https://github.com/biopragmatics/bioregistry/issues/959
