### ISSUE TITLE
Add prefix [worms]

### ISSUE THREAD

**Issue by megbalk** [biopragmatics/bioregistry#465]
### Prefix

worms

### Name

World Register of Marine Species

### Homepage

https://www.marinespecies.org

### Description

identifier in the World Register of Marine Species

### Example Local Unique Identifier

[AlphaID:145548](urn:lsid:marinespecies.org:taxname:145548)

### Regular Expression Pattern for Local Unique Identifier

[1-9]\d{0,6}

### URI Format String

https://www.marinespecies.org/aphia.php?p=taxdetails&id=145548

### Wikidata Property

[P850](https://www.wikidata.org/wiki/Property:P850)

### Contributor Name

Meghan Balk

### Contributor GitHub

megbalk

### Contributor ORCiD

0000-0003-2699-3066

**Comment by cthoyt** [comment]
@megbalk looks like this is already in the bioregistry at https://bioregistry.io/registry/worms, can you confirm that's the same and close this issue if so?

**Comment by megbalk** [comment]
It is! Sorry, I also thought this one was still pending.
