### ISSUE TITLE
Add way to indicate provider-preferred IRIs for use in semweb contexts

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#47]
one of the purposes of https://github.com/prefixcommons/biocontext/ is to provide a mechanism to map standardized prefixes to URIs and back, acting as an interoperation layer between semweb world of URIs and bio world of CURIEs/prefixed IDs.

We could explore retiring biocontext in place of bioregistry if we can get a way to indicate the provider preferred way of indicating a semweb/OWL URI.

For example, for any OBO ontology, the OBO PURL is canonical (OK, there are wrinkles when it comes to NCIT and FMA)

As far as I can tell there isn't really a direct way of getting this in bioregistry:

```
  "fbbt": {
    "bioportal": {
      "name": "Drosophila Gross Anatomy Ontology",
      "prefix": "FB-BT"
    },
    "example": "00007294",
    "go": {
      "formatter": "http://flybase.org/cgi-bin/fbcvq.html?query=FBbt:$1",
      "homepage": "http://flybase.org/",
      "name": "Drosophila gross anatomy",
      "prefix": "FBbt"
    },
    "mappings": {
      "bioportal": "FB-BT",
      "go": "FBbt",
      "prefixcommons": "FBbt"
    },
    "obofoundry": {
      "contact": "cp390@cam.ac.uk",
      "contact.label": "Clare Pilgrim",
      "deprecated": false,
      "download.obo": "https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbbt.obo",
      "homepage": "http://purl.obolibrary.org/obo/fbbt",
      "license": "CC-BY",
      "name": "Drosophila gross anatomy",
      "prefix": "fbbt",
      "repo": "https://github.com/FlyBase/drosophila-anatomy-developmental-ontology.git"
    },
    "ols": {
      "description": "An ontology of Drosophila melanogaster anatomy.",
      "download": "http://purl.obolibrary.org/obo/fbbt.owl",
      "homepage": "http://purl.obolibrary.org/obo/fbbt",
      "license": "https://creativecommons.org/licenses/by/3.0/",
      "name": "Drosophila Anatomy Ontology (DAO)",
      "prefix": "fbbt",
      "version": "2021-05-11",
      "version.iri": "http://purl.obolibrary.org/obo/fbbt/releases/2021-05-11/fbbt.owl"
    },
    "ols_version_date_format": "%Y-%m-%d",
    "pattern": "^\\d{8}$",
    "prefixcommons": {
      "formatter": "http://purl.obolibrary.org/obo/FBbt_$1",
      "is_identifiers": false,
      "is_obo": true,
      "prefix": "FBbt"
    },
    "synonyms": [
      "FBbt_root",
      "FBbt"
    ]
  },
```

the OBO PURL is there under `prefixcommons`, which I believe is coming from https://github.com/prefixcommons/biocontext/ which is itself an aggregator, and the real source for this is the OBO registry 

http://purl.obolibrary.org/meta/obo_prefixes.ttl

Maybe this goes against the bioregistry philosophy of being an aggregation of others' json blobs, but I think this could be quite useful.

**Comment by cthoyt** [comment]
This has been taken care of with https://github.com/biopragmatics/bioregistry/tree/main/exports/contexts
