### ISSUE TITLE
Add prefix [Open Tree of Life ID]

### ISSUE THREAD

**Issue by megbalk** [biopragmatics/bioregistry#470]
### Prefix

otol

### Name

Open Tree of Life

### Homepage

https://tree.opentreeoflife.org

### Description

identifier for an entity in Open Tree of Life

### Example Local Unique Identifier

3905431

### Regular Expression Pattern for Local Unique Identifier

^[1-9]\d*$

### URI Format String

https://tree.opentreeoflife.org/taxonomy/browse?id=$1

### Wikidata Property

P9157

### Contributor Name

Meghan Balk

### Contributor GitHub

megbalk

### Contributor ORCiD

0000-0003-2699-3066

### Additional Comments

use NCBI Taxon

**Comment by cthoyt** [comment]
This isn't related to http://tolweb.org/tree/ (https://bioregistry.io/registry/tol), right?

**Comment by megbalk** [comment]
I think this is different. Since tolweb already has a prefix, perhaps this one should be otol?

**Comment by cthoyt** [comment]
Great idea!

**Comment by megbalk** [comment]
looks like you updated it, thank you!
