### ISSUE TITLE
Add prefix [Tree of Life Web Project ID]

### ISSUE THREAD

**Issue by megbalk** [biopragmatics/bioregistry#471]
### Prefix

tol.webproj

### Name

Tree of Life Web Project ID

### Homepage

http://tolweb.org

### Description

identifier in the Tree of Life Web Project

### Example Local Unique Identifier

16952

### Regular Expression Pattern for Local Unique Identifier

[1-9]\d*

### URI Format String

http://tolweb.org/$1

### Wikidata Property

[P5221](https://www.wikidata.org/wiki/Property:P5221)

### Contributor Name

Meghan Balk

### Contributor GitHub

megbalk

### Contributor ORCiD

0000-0003-2699-3066

**Comment by cthoyt** [comment]
I think this one is the same as https://bioregistry.io/registry/tol, can you confirm?

**Comment by megbalk** [comment]
It is! Sorry, I thought it was still pending.

**Comment by megbalk** [comment]
Do you need to distinguish from ToL?
