### ISSUE TITLE
`curie_from_iri()` too slow

### ISSUE THREAD

**Issue by joeflack4** [biopragmatics/bioregistry#480]
## Summary
It seems too slow. Each term takes about 2-3 seconds to convert, it looks like.

#### Code
```python
    prefix_map = {'ICD10WHO': 'https://icd.who.int/browse10/2019/en#/'}
    terms = list(df['term_id'])
    new = []
    t1 = datetime.now()
    for i in range(0, len(terms)):
        term = terms[i]
        new.append(uri_to_curie(term, prefix_map=prefix_map))
        if i % 10 == 0:
            t2 = datetime.now()
            print(f'{i} conversions in {(t2 - t1).seconds} seconds')
```

#### Results
```
0 conversions in 2 seconds
10 conversions in 29 seconds
20 conversions in 59 seconds
30 conversions in 83 seconds
```

**Comment by joeflack4** [comment]
Slightly related: #479

**Comment by cthoyt** [comment]
Sorry, but the code you put in your example isn't reproducible - it's missing imports. Based on the other linked issues, I might guess this is OAK code. If you update so I can directly copy/paste this to run myself (also consider fixing the code formatting) then I can try it too.

Not to say Bioregistry doesn't have some performance issues in URI parsing - there's already an issue #437 for this. I'm following up by building a more principled and general benchmarking suite in https://github.com/biopragmatics/bioregistry/pull/481.

I've already figured out that the slow part is the code is inefficiently re-generating the prefix map over and over. I can cache this and speed up gets to ~1K URIs parsed per second.

**Comment by cthoyt** [comment]
So the solution is to update your code to use the caching mechanism in `ensure_prefix_list()` like in the following example:

```python
>>> from bioregistry import parse_iri, ensure_prefix_list
>>> prefix_map = {"chebi": "https://example.org/chebi:"}
>>> prefix_list = ensure_prefix_list(prefix_map)
>>> parse_iri("https://example.org/chebi:1234", prefix_map=prefix_list)
('chebi', '1234')
```

**Comment by joeflack4** [comment]
> Sorry, but the code you put in your example isn't reproducible - it's missing imports. Based on the other linked issues, I might guess this is OAK code. If you update so I can directly copy/paste this to run myself (also consider fixing the code formatting) then I can try it too.
My bad! Didn't intend it to be reproducible so easily. I meant for the imports to be inferred, but I also was calling my wrapper function (not OAK's), `uri_to_curie()` rather than `curie_from_iri()`. Fixed.
