### ISSUE TITLE
Perfecting the project-specific prefix maps

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#491]
I am looking at the latest update of the OBO context and have a few questions.

## Replaced OBO PURLs when source ontologies are obsolete

Is this a general design decision? Not to include OBO prefixes of deprecated sources at all? Or if they conflict with something else?
 
```
"ADW": "http://purl.obolibrary.org/obo/ADW_",
"ADW": "https://animaldiversity.org/accounts/",
"IP": "http://purl.obolibrary.org/obo/IPR_",
"IP": "https://www.ebi.ac.uk/interpro/entry/",
```

## Adding some weird sounding prefixes.. Why?

```
"Geomames": "https://www.geonames.org/", (typo?)
"Geonamaes": "https://www.geonames.org/", (typo?)
"IC9CM": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=", (missing D?)
"NCBI Taxonomy": "http://purl.obolibrary.org/obo/NCBITaxon_", (prefixes with spaces?)
```

## Shouldnt this context be a source-unique bi-map?

There are many alternative ICD10 (and SNOMEDCT) prefixes in our obo context, lower case, upper case, variations. I would only want 1! For URI to CURIE conversions, how will my tools understand which prefix to pick (based on the context alone)? This is what we have:

```
"IC9CM": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
"ICD": "http://apps.who.int/classifications/icd10/browse/2010/en#/",
"ICD-10": "http://apps.who.int/classifications/icd10/browse/2010/en#/",
"ICD-11": "https://icd.who.int/browse11/l-m/en#/http://id.who.int/icd/entity/",
"ICD10": "http://apps.who.int/classifications/icd10/browse/2010/en#/",
"ICD10CM": "https://icd.codes/icd10cm/",
"ICD9": "http://www.icd9data.com/getICD9Code.ashx?icd9=",
"ICD9CM": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
"ICD9CM_2005": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
"ICD9CM_2006": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
"ICD9_2005": "http://www.icd9data.com/getICD9Code.ashx?icd9=",
"ICDCM_2005": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
"icd10cm": "https://icd.codes/icd10cm/",
"icd10pcs": "https://www.findacode.com/code.php?set=ICD10PCS&c=",
"icd11": "https://icd.who.int/browse11/l-m/en#/http://id.who.int/icd/entity/",
"icd9": "http://www.icd9data.com/getICD9Code.ashx?icd9=",
"icd9cm": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
```

This is what I want:

```
"ICD11": "https://icd.who.int/browse11/l-m/en#/http://id.who.int/icd/entity/", <- really weird expansion. Lets lobby WHO for a PURL system. We can do that.
"ICD10CM": "https://icd.codes/icd10cm/",
"ICD9CM": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
"ICD10PCS": "https://www.findacode.com/code.php?set=ICD10PCS&c=",
```

I can see why we need these prefixes (historical analysis) but can't we deprecate them? `IC9CM` looks like a typo, and the 2005, 2006 prefixes should not appear in these project based curie maps. What are the options?

**Comment by cthoyt** [comment]
So just to be clear, there are two exports of the OBO context:
1. Includes synonyms (https://github.com/biopragmatics/bioregistry/blob/main/exports/contexts/obo_synonyms.context.jsonld)
2. Doesn't include synonyms (https://github.com/biopragmatics/bioregistry/blob/main/exports/contexts/obo.context.jsonld)

I figured the one that doesn't include synonyms is the better one - this is guaranteed to be a bi-directional map.

> ## Replaced OBO PURLs when source ontologies are obsolete
> 
> Is this a general design decision? Not to include OBO prefixes of deprecated sources at all? Or if they conflict with something else?
> 
> ```
> "ADW": "http://purl.obolibrary.org/obo/ADW_",
> "ADW": "https://animaldiversity.org/accounts/",
> "IP": "http://purl.obolibrary.org/obo/IPR_",
> "IP": "https://www.ebi.ac.uk/interpro/entry/",
> ```

What's the desired functionality? I don't really understand what you wrote here.

> ## Adding some weird sounding prefixes.. Why?
> 
> ```
> "Geomames": "https://www.geonames.org/", (typo?)
> "Geonamaes": "https://www.geonames.org/", (typo?)
> "IC9CM": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=", (missing D?)
> "NCBI Taxonomy": "http://purl.obolibrary.org/obo/NCBITaxon_", (prefixes with spaces?)
> ```

Some ontologies were resistant to accepting PRs for their typos and _very_ nonstandard prefix usage (e.g., the `NCBI Taxonomy` example), so I have begun including them as "synonyms" in some records

> ## Shouldnt this context be a source-unique bi-map?
> 
> There are many alternative ICD10 (and SNOMEDCT) prefixes in our obo context, lower case, upper case, variations. I would only want 1! For URI to CURIE conversions, how will my tools understand which prefix to pick (based on the context alone)? This is what we have:
> 
> ```
> "IC9CM": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
> "ICD": "http://apps.who.int/classifications/icd10/browse/2010/en#/",
> "ICD-10": "http://apps.who.int/classifications/icd10/browse/2010/en#/",
> "ICD-11": "https://icd.who.int/browse11/l-m/en#/http://id.who.int/icd/entity/",
> "ICD10": "http://apps.who.int/classifications/icd10/browse/2010/en#/",
> "ICD10CM": "https://icd.codes/icd10cm/",
> "ICD9": "http://www.icd9data.com/getICD9Code.ashx?icd9=",
> "ICD9CM": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
> "ICD9CM_2005": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
> "ICD9CM_2006": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
> "ICD9_2005": "http://www.icd9data.com/getICD9Code.ashx?icd9=",
> "ICDCM_2005": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
> "icd10cm": "https://icd.codes/icd10cm/",
> "icd10pcs": "https://www.findacode.com/code.php?set=ICD10PCS&c=",
> "icd11": "https://icd.who.int/browse11/l-m/en#/http://id.who.int/icd/entity/",
> "icd9": "http://www.icd9data.com/getICD9Code.ashx?icd9=",
> "icd9cm": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
> ```
> 
> This is what I want:
> 
> ```
> "ICD11": "https://icd.who.int/browse11/l-m/en#/http://id.who.int/icd/entity/", <- really weird expansion. Lets lobby WHO for a PURL system. We can do that.
> "ICD10CM": "https://icd.codes/icd10cm/",
> "ICD9CM": "http://icd9cm.chrisendres.com/index.php?action=search&srchtext=",
> "ICD10PCS": "https://www.findacode.com/code.php?set=ICD10PCS&c=",
> ```
> 
> I can see why we need these prefixes (historical analysis) but can't we deprecate them? `IC9CM` looks like a typo, and the 2005, 2006 prefixes should not appear in these project based curie maps. What are the options?

Adding an "exclude" list to the configuration might help alleviate this w.r.t. the OBO context, but again I think this is a bit more confusing since you're looking at the synonyms export

**Comment by matentzn** [comment]
> So just to be clear, there are two exports of the OBO context:

IIIIIIIEEEEE! Sorry man didn't know that, and this is great. I am using that and following up on this later.

> What's the desired functionality? I don't really understand what you wrote here.

```
"IP": "http://purl.obolibrary.org/obo/IPR_",
"IP": "https://www.ebi.ac.uk/interpro/entry/",
```

I guess I would leave the former as synonym, since the "deprecated" OBO ontologies still exist and still have the same PURL..

> Some ontologies were resistant to accepting PRs for their typos and very nonstandard prefix usage (e.g., the NCBI Taxonomy example), so I have begun including them as "synonyms" in some records

Excellent makes total sense. Total.

> Adding an "exclude" list to the configuration might help alleviate this w.r.t. the OBO context, but again I think this is a bit more confusing since you're looking at the synonyms export

I am not to worried either way but being able to exclude specific prefixes (or sources?) would be nice for the custom config. In any case.

Thanks the synonym free map dealt with my immediate questions, so feel free to close, nothing burning on my end.
