### ISSUE TITLE
Add prefix [ddinter]

### ISSUE THREAD

**Issue by sierra-moxon** [biopragmatics/bioregistry#492]
### Prefix

ddinter

### Name

Curated Drug-Drug Interactions Database

### Homepage

http://ddinter.scbdd.com/

### Description

DDInter is a comprehensive, professional, and open-access database specific to drug-drug interactions. It provides abundant annotations for each DDI association including mechanism description, risk levels, management strategies, alternative medications, etc. to improve clinical decision-making and patient safety.

### Example Local Unique Identifier

DDInter20

### Regular Expression Pattern for Local Unique Identifier

^DDInter[0-9]+$

### URI Format String

http://ddinter.scbdd.com/ddinter/drug-detail/$1/

### Contributor Name

Sierra Moxon

### Contributor GitHub

sierra-moxon

### Contributor ORCiD

0000-0002-8719-7760

### Contact Name

Dr. Dongsheng Cao

### Contact ORCiD

0000-0003-3604-3785

### Additional Comments

for contacting this resource, they provide this email address `yjc @ nudt.edu.cn` 
request generated via NCATS Translator

**Comment by bgyori** [comment]
Thanks @sierra-moxon this is great! I noticed that DDInter has identifiers not only for drugs but also interactions e.g., http://ddinter.scbdd.com/ddinter/interact/1122888/. So I think we may want to introduce multiple prefixes for ddinter like `ddinter.drug` and `ddinter.interaction`. Perhaps @cthoyt can look into this later.

**Comment by cthoyt** [comment]
Will take care of these tomorrow. There’s also a banana in these identifiers, might be interesting to see if that’s the case for the interactions as well
