### ISSUE TITLE
Add prefix `time`

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#505]
### Prefix

time

### Name

Time Ontology in OWL

### Homepage

https://www.w3.org/TR/owl-time/

### Description

OWL-Time is an OWL-2 DL ontology of temporal concepts, for describing the temporal properties of resources in the world or described in Web pages. The ontology provides a vocabulary for expressing facts about topological (ordering) relations among instants and intervals, together with information about durations, and about temporal position including date-time information. Time positions and durations may be expressed using either the conventional (Gregorian) calendar and clock, or using another temporal reference system such as Unix-time, geologic time, or different calendars.

### Example Local Unique Identifier

DateTimeDescription

### URI Format String

http://www.w3.org/2006/time#$1

### Contributor Name

Charles Tapley Hoyt

### Contributor GitHub

cthoyt

### Contributor ORCiD

0000-0003-4423-4370

**Comment by cthoyt** [comment]
@lubianat would you please review this one? We can go through that together

**Comment by lubianat** [comment]
@cthoyt I could, yes! but it looks like it is solved?

**Comment by cthoyt** [comment]
I realized that I needed this for something else, but I still think it would be cool if you could take a look at it (make sure the website is right, the URI format actually makes sense, etc.)
