### ISSUE TITLE
Add prefix [inaturalist.observation]

### ISSUE THREAD

**Issue by oolonek** [biopragmatics/bioregistry#517]
### Prefix

inaturalist.observation

### Name

iNaturalist Observation

### Homepage

https://www.inaturalist.org/observations

### Description

The identifier for iNaturalist observations at https://www.inaturalist.org/observations

### Example Local Unique Identifier

36010371

### Regular Expression Pattern for Local Unique Identifier

^[1-9]\d*$

### URI Format String

`https://www.inaturalist.org/observations/$1`

### Wikidata Property

[P5683](https://www.wikidata.org/wiki/Property:P5683)

### Contributor Name

Pierre-Marie Allard

### Contributor GitHub

oolonek

### Contributor ORCiD

0000-0003-3389-2191

**Comment by cthoyt** [comment]
Thanks @oolonek! I made a tiny update to the syntax in the PR for your request and it's all ready to merge now. I also added two more iNaturalist prefixes for users and places as well.
