### ISSUE TITLE
Add prefix confident.event

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#519]
### Prefix

confident.event

### Name

ConfIDent Event

### Homepage

https://www.confident-conference.org/index.php/Category:Event

### Description

ConfIDent makes descriptive metadata on conferences and other formats of scientific events permanently accessible in a high quality through automated processes and scientific data curating.

### Example Local Unique Identifier

37af84f2-bfd7-4653-b608-eaff44febba6

### Regular Expression Pattern for Local Unique Identifier

^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$

### URI Format String

https://www.confident-conference.org/index.php/Event:$1

### Contributor Name

Charles Tapley Hoyt

### Contributor GitHub

cthoyt

### Contributor ORCiD

0000-0003-4423-4370

### Additional Comments

@StroemPhi do you want to be listed as contact for this? or do you know who the right person is?

**Comment by StroemPhi** [comment]
Moin @cthoyt, if you need a human contact yes, you can use me as fallback option, but we prefer the functional email address (ConfIDent [at] tib.eu) for such inquiries. And also, as mention on Twitter this morning, this ConfIDent identifier, although resolvable, is not planned to be cited as we want to mint a DataCite DOI for each ConfIDent entry of an event or series.

**Comment by cthoyt** [comment]
It's a core value of the Bioregistry to promote transparency - group email addresses are obviously antithetical to this so it's our policy to annotate single points of contact. Thanks :)

Bioregistry also doesn't touch the issues of citations, so nothing to comment on there. One way you can consider resolving this is by copying what Zenodo, bioRxiv, and many other DOI-minting resources do - use the local unique identifier as the local part of your DOIs (though this would require reorganizing the local unique identifiers quite a bit)

**Comment by StroemPhi** [comment]
Point 1: got it, so please use me: [0000-0002-1595-3213](https://orcid.org/0000-0002-1595-3213)

Point 2: I don't think I can follow exactly, you mean having the ConfIDent UUID as suffix also for the DOIs we mint, so that only the prefix in the CURIE would be different?

**Comment by cthoyt** [comment]
Point 2:

Here's a zenodo record from the front page: https://zenodo.org/record/7013120. It has local unique identifier `7013120` in the semantic space [`zenodo.record`](https://bioregistry.io/registry/zenodo.record). The DOI associated with it is https://doi.org/10.5281/zenodo.7013120. Note that the DOI shares the local unique identifier from the semantic space itself.

DOIs would look silly (if it's even allowed) if you used UUIDs in them (e.g., for events) or letter-based codes (e.g., for event series)

**Comment by StroemPhi** [comment]
Thx, for the example! And indeed the UUIDs would be too much/ugly (don't think the DataCite schme would prohibit it though). As the SMW plattform is still in beta, the migration from the old Open Research plattform is not yet finished, which is why some series still have a letter based ID. I'll make sure to try a PR here, once the series have also been switched to UUID.

**Comment by cthoyt** [comment]
My suggestion is just use numbers (i.e., strings matching `^\\d+$`) for both.
