### ISSUE TITLE
Crop Ontologies' URIs are incorrect

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#527]
The canonical form for all CO_nnn PURLs are

`http://www.cropontology.org/rdf/CO_NNN:NNNNNNN` (http, `www` included)

It so happens this redirects to `https://cropontology.org/rdf/CO_NNN:NNNNNNN` (https, no `www`). However, that is just a web address, not the PURL used in the OWL

Currently bioregistry has

     - https://bioregistry.io/reference/co_320:0000965 => 
     - https://www.cropontology.org/rdf/CO_324:0000965 =>
     - https://cropontology.orgrdf/CO_320:0000965

Which is a 404. The CO folks could probably do a better job setting up their apache config, but nevertheless the correct OWL PURLs should be used

I also recommend setting preferred prefix for upper case for all of these

**Comment by cthoyt** [comment]
@elizabetharnaud  can you comment on this?

**Comment by qlands** [comment]
Hi @cthoyt 

Can you explain the problem? All urls are https

**Comment by cthoyt** [comment]
@qlands thanks for clarifying, I think the original issue supposed that they should be using http. It also brought up a good point that these URLs don't seem to redirect properly, it would be great if you could communicate that to the right person to fix the redirects.

**Comment by cmungall** [comment]
@cthoyt - ah, this is odd. Perhaps the OLS is loading an old version?

E.g.

https://www.ebi.ac.uk/ols/ontologies/co_325/terms?iri=http%3A%2F%2Fwww.cropontology.org%2Frdf%2FCO_325%3A0000536

Uses:
http://www.cropontology.org/rdf/CO_325:0000536

<img width="753" alt="image" src="https://user-images.githubusercontent.com/50745/187781514-3efbd60a-e762-400f-87d3-92db6f15fbc3.png">

However, indeed as you point out, when you resolve the PURL the Class URIs are of the form https://cropontology.org/rdf/CO_325:0000536. These do resolve

And when I look at
https://cropontology.org/rdf/CO_325:0000536

It is indeed https

So I think I was mislead by taking the content of OLS as being canonical. I will make an issue for OLS to refresh. Maybe the ontology PURLs switched from http to https recently (which would mean they are not actually PURLs...)

@qlands can you confirm to be sure that your OWL class URIs will have the following structure moving forward:

https://cropontology.org/rdf/CO_325:0000536

more generally:

https://cropontology.org/rdf/CO_NNN:NNNNNNN

If so, the action on the bioregistry side is easy, remove the `.www` as this doesn't resolve, and isn't the URI used in the OWL
