### ISSUE TITLE
Add prefix sphn

### ISSUE THREAD

**Issue by deepakunni3** [biopragmatics/bioregistry#535]
### Prefix

sphn

### Name

Swiss Personalized Health Network

### Homepage

https://www.sphn.ch

### Description

The Swiss Personalized Health Network is a national infrastructure initiative with the aim to develop, implement and validate coordinated data infrastructures in order to make health-relevant data interoperable and shareable for research in Switzerland. The SPHN RDF schema builds the foundation for all data exchanges within the SPHN by integrating semantic information defined in the SPHN Dataset (https://sphn.ch/document/sphn-dataset/).

### Example Local Unique Identifier

Allergy

### Regular Expression Pattern for Local Unique Identifier

^\S+$

### URI Format String

https://biomedit.ch/rdf/sphn-ontology/sphn#$1

### Contributor Name

Deepak Unni

### Contributor GitHub

deepakunni3

### Contributor ORCiD

0000-0002-3583-7340

### Contact Name

SPHN Data Coordination Center (dcc@sib.swiss)

### Additional Comments

The `sphn` prefix refers to concepts and properties defined in the SPHN RDF schema.

**Comment by cthoyt** [comment]
Hi @deepakunni3, the contact person must correspond to exactly one individual, not being a group email address. Can you also double check the regex is correct? Does \S mean any text? Or is that what \w is for?

**Comment by deepakunni3** [comment]
Hi @cthoyt ! Thanks for the quick response. 

- The contact person being a group email address was because it improves reachability instead of the correspondence being restricted to just one individual. Let me check with the team and get back to you.
- The `^\S+$` means any text (including numbers, characters, letters). `\w` would be just numbers and letters

**Comment by cthoyt** [comment]
While group emails improve reachability, they diffuse responsibility. We’ll need a person’s name, email, and orcid if we want to annotate this. By the way this is motivated by the Obo guidelines

**Comment by deepakunni3** [comment]
Sure, I'll report back with a proper email 👍

**Comment by cthoyt** [comment]
@vtoure is pretty recent on the blame for https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-ontology/-/blame/master/ontology/sphn_ontology.owl, maybe she's the right one?
