### ISSUE TITLE
Add prefix glycosciences

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#537]
### Prefix

glycosciences

### Name

Glycosciences.DB

### Homepage

http://www.glycosciences.de/database/

### Description

A database to support glycobiology and glycomics research. Its main focus is on 3D structures, including 3D structure models as well as references to PDB entries that feature carbohydrates.

### Example Local Unique Identifier

1

### Regular Expression Pattern for Local Unique Identifier

^\d+$

### URI Format String

http://www.glycosciences.de/database/start.php?action=explore_linucsid&linucsid=$1

### Contributor Name

Chris Mungall

### Contributor GitHub

cmungall

### Contributor ORCiD

0000-0002-6601-2165

### Contact Name

Thomas Lütteke

### Contact ORCiD

0000-0002-7140-9933

### Additional Comments

1. Note the website and paper https://academic.oup.com/nar/article/47/D1/D1195/5144145 refer to the database as glycosciences.DB, but the period is conventionally used as an authority-type tuple separator in bioregistry, so we should ask this group how they want to be referred to.
2. I am not totally sure what the identifier lifecycle is for LINUCS IDs. Note these IDs are different from LINCUS strings, which are analogous to SMILES/INCHI/etc (see also #460)

**Comment by cthoyt** [comment]
- I think we can drop the dot delimiter and use `glycosciencesdb` as the prefix. We can always mint synonyms later, if necessary.
- I've updated the issue to have only the example LUID `1` instead of the full URI in the "Example Local Unique Identifier" field

The website says [Thomas Lütteke](http://www.glycosciences.de/people/index.php?name=thomas) (thomas@luetteke-online.de, email available from the paper as corresponding author, https://orcid.org/0000-0002-7140-9933) is the maintainer.

**Comment by cthoyt** [comment]
@glycosciences do you want to comment on this? We're registering your database in the Bioregistry to make it easier for people to figure out how to refer to entries in your database in a standard way.

**Comment by cthoyt** [comment]
Also looking at this twice, the identifier seems to be for the `linucsid` - should this semantic space be named `linucs` instead? I will merge this now for experience but I think it would be worth reinvestigating this.

**Comment by glycosciences** [comment]
@cthoyt linucs is the internal notation used to describe glycan structures. Each unique linucs string in the database gets an id, the linucsid. I will add further comments to #538
