### ISSUE TITLE
Change point of contact for sphn prefix

### ISSUE THREAD

**Issue by deepakunni3** [biopragmatics/bioregistry#544]
### Prefix

sphn

### Explanation

This request is a continuation of a previous ticket: https://github.com/biopragmatics/bioregistry/issues/535

@vtoure has done a great deal of work on the SPHN RDF schema but we would prefer to add Sabine Oesterle (Sabine.Oesterle@sib.swiss) as the point of contact for this prefix resource.

**Email:** Sabine.Oesterle@sib.swiss
**GitLab:** @sabine_oesterle
**ORCID:** 0000-0003-3248-7899

Sabine is the team lead of our Data Interoperability team and is the appropriate point of contact for this resource.

### Contributor ORCID

0000-0002-3583-7340

**Comment by cthoyt** [comment]
Since we're doing development on GitHub, a GitLab handle isn't much use. Can you please have her create an account on GitHub and make sure that she's got email notifications turned on?

**Comment by deepakunni3** [comment]
If GitHub account is required then better to have me as the point of contact for this prefix.

**Comment by cthoyt** [comment]
It's not required but it does beg the question if the contact person isn't interested/able to make themselves available on a common public channel if they're the best choice. Either way is fine for me

**Comment by deepakunni3** [comment]
The reason why I suggested my name is because:
- I would like to take the lead on certain things that are pertaining to the SPHN
- I am much more active on GitHub, whereas Sabine is active on GitLab

I do not think it is a lack of willingness or interest to be available for public discussions :) 

If this seems like a compromise then I can ask Sabine to make a GitHub account to be linked as part of this resource.
