### ISSUE TITLE
Update regular expression pattern for RefSeq non-redundant proteins

### ISSUE THREAD

**Issue by slobentanzer** [biopragmatics/bioregistry#545]
### Prefix

refseq

### Old Regular expression pattern

`^(((AC|AP|NC|NG|NM|NP|NR|NT|NW|XM|XP|XR|YP|ZP)_\d+)|(NZ\_[A-Z]{2,4}\d+))(\.\d+)?$`

### New Regular Expression Pattern

`^(((AC|AP|NC|NG|NM|NP|NR|NT|NW|WP|XM|XP|XR|YP|ZP)_\d+)|(NZ\_[A-Z]{2,4}\d+))(\.\d+)?$`

### Explanation

The current regex does not include "WP_" non-redundant identifiers: https://www.ncbi.nlm.nih.gov/refseq/about/nonredundantproteins/

### Contributor ORCID

0000-0003-3399-6695

**Comment by cthoyt** [comment]
hi @slobentanzer can you please give some concrete examples of identifiers where the current regex fails but this one works?

**Comment by slobentanzer** [comment]
I had this one in the Open Targets graph: WP_029104145.1

**Comment by cthoyt** [comment]
Great, thanks @slobentanzer for the suggestion. I've added an update in #546 and attributed you appropriately. This change will be auto-deployed tonight. However, if there's a pressing reason you need it ASAP, I can also trigger a deploy now manually.

**Comment by slobentanzer** [comment]
It's not pressing, no. Thanks a lot! :)
