### ISSUE TITLE
is_valid_curie returns None instead of False for an invalid identifier

### ISSUE THREAD

**Issue by dhimmel** [biopragmatics/bioregistry#558]
Using bioregistry 0.5.92:

```py
_curie = "ICD9:BAAAAAAAAD"
_curie = bioregistry.normalize_curie(_curie)
print(_curie)
_curie = bioregistry.is_valid_curie(_curie)
print(_curie)
```

Output:

```
icd9:BAAAAAAAAD
None
```

Source

https://github.com/biopragmatics/bioregistry/blob/2223156c869d05682e24a3409eb9eded06c27297/src/bioregistry/resource_manager.py#L946-L988

Is None the expected output? Any reason why None is ever desirable? Could change type signature to `-> bool`?

**Comment by dhimmel** [comment]
What I'm trying to do is to validate that a CURIE has a known prefix and that the identifier matches the regex pattern.

**Comment by cthoyt** [comment]
None is output if there's no pattern available for the known prefix

https://github.com/biopragmatics/bioregistry/blob/14c6a5b89a24ef2371aea41d54b0193efd87b88c/src/bioregistry/schema/struct.py#L1491-L1496

**Comment by dhimmel** [comment]
> None is output if there's no pattern available for the known prefix

I see, sort of an unexpected behavior. Even when there is a pattern, matching the pattern doesn't actually guarantee the identifier is valid. So my intuition would be to return True when pattern is missing. True for no detectable problem, False for detectable problem.

**Comment by dhimmel** [comment]
Furthermore None evaluates to False in a boolean context, such that this could trap some users.

**Comment by bgyori** [comment]
I tend to agree with @dhimmel that for a *known* and registered prefix like `icd9`, if the identifier pattern is missing, returning `True` would be appropriate behavior. Perhaps it should be documented more explicitly in the docstring how downstream users can check if an identifier pattern exists or not. Another option is to add a parameter to the `is_valid_identifier` function like `allow_unknown_pattern`.
