### ISSUE TITLE
Update to MolMeDB resource

### ISSUE THREAD

**Issue by DominikMartinat** [biopragmatics/bioregistry#564]
### Prefix

molmedb

### Explanation

Hi.

Contact person for MolMeDB is Karel Berka wit ORCID 0000-0001-9472-2589 and mail address karel.berka@upol.cz.

MolMeDB homepage should be updated to https://molmedb.upol.cz/.

And perhaps reference could be also added https://doi.org/10.1093/database/baz078.

### Contributor ORCID

0000-0001-6611-7883

**Comment by cthoyt** [comment]
Thank you @DominikMartinat! I have made the appropriate update and attributed you appropriately :)
