### ISSUE TITLE
Allen brain atlas atlas IDs do not resolve

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#566]
I believe you got these Allen Institue ontologies listed in [bioregistry.collection:0000005](https://bioregistry.io/collection/0000005) from uberon:

- mba (mouse)
- hba (human)
- dhba (developing human)
- dmba (developing mouse)
- pba (primate)

However, none resolve:

https://bioregistry.io/reference/mba:688

I am not sure what to suggest here, as I have been unable to get a clear answer here

See:

https://github.com/obophenotype/uberon/issues/1419

I think we should keep an issue open on one of our trackers until this is either resolved or there is a very explicit "won't fix"

**Comment by cthoyt** [comment]
All of these now have URI formats for resolving to the static sites on https://biopragmatics.github.io/providers/  including:

1. https://biopragmatics.github.io/providers/mba
2. https://biopragmatics.github.io/providers/hba
3. https://biopragmatics.github.io/providers/dhba
4. https://biopragmatics.github.io/providers/dmba
5. https://biopragmatics.github.io/providers/pba
