### ISSUE TITLE
mint and intact.molecule examples do not resolve

### ISSUE THREAD

**Issue by slobentanzer** [biopragmatics/bioregistry#567]
Hi Charlie,
The example IDs for MINT (https://bioregistry.io/reference/mint:MINT-10000) and intact.molecule (https://bioregistry.io/reference/intact.molecule:EBI-366083) do not resolve. MINT links lead to "not found", while the intact.molecule links lead to the IntAct start page.

**Comment by cthoyt** [comment]
in fact I became aware of these myself yesterday and mixed up the fix with some other improvements to banana processing in #563 but I can update these resolutions in a separate PR

**Comment by cthoyt** [comment]
Looking more closely, I don't think that IntAct actually has an endpoint for resolving the `intact.molecule` namespace (anymore?). Are you aware of where this should go? 

For example, I was looking at https://www.ebi.ac.uk/intact/details/interaction/EBI-22263356#participants, which lists several participants' accessions (e.g., `EBI-22263364`), but without links.

**Comment by slobentanzer** [comment]
I am not sure whether there is an endpoint any more; I just know that they recently made some changes to the API, maybe they removed support for these IDs. I also don't know if they are using that namespace at all, any more (who BTW makes these decisions, and where are they recorded?). If you want I can ask them via email.

**Comment by cthoyt** [comment]
Bioregistry is a descriptive resource - it tries to give a good overview of how stuff _actually_ works and the most practical perspective. It means sometimes stuff gets out of sync - i.e. the IntAct people aren't going to proactively update bioregistry when they break their own APIs, that's up to the community to notice and fix.

One Idea we have for this is the health report https://github.com/biopragmatics/bioregistry/actions/workflows/health.yml but this needs a better looking front-end (see #453)

**Comment by slobentanzer** [comment]
Of course; and it's a good thing to be pragmatic. My question was rather how to decide in this case (and who decides) whether the `intact.molecule` namespace still is a thing or whether it is abandoned. I for one did not know whether to map anything in the OTAR graph to `intact.molecule`, because there is no namespace annotation as far as I could see. All things coming from intact have the source `intact` (but source names are not CURIE prefixes). In fact, I only discovered there was such a thing as `intact.molecule` by browsing Bioregistry in the first place.

The health report is a great feature, but the provider check seems to have some dependency issue. :D

**Comment by cthoyt** [comment]
Yeah, it's not exactly clear if this namespace even exists anymore (or if it was ever different from `intact`). Since Bioregistry is a community resource, anyone can suggest stuff either via an issue or PR. Then whoever is available from @biopragmatics/bioregistry-reviewers (often me, but also several others) can facilitate discussion, decide what to do, and either make the changes or review a PR with external changes.

Tbh i'm not sure what to do here since it's not obvious how to get the entire set of intact identifiers. If you figure that one out, please let me know.

In the mean time for biocypher, I would suggest mapping out into `uniprot` or `complexportal` whenever possible. See discussion at https://twitter.com/cthoyt/status/1252345260740456453.

**Comment by cthoyt** [comment]
btw @slobentanzer you should join the OBO Foundry slack https://join.slack.com/t/obo-communitygroup/shared_invite/zt-1ecgp376e-~ldRtnCtjmDRiptaqWYg2g where we have a channel for bioregistry called `#prefixes`

**Comment by cthoyt** [comment]
Update, MINT IDs resolve properly now. IntAct molecule IDs still do not because there is no service to do so at the moment.
