### ISSUE TITLE
Update default KISAO resolver

### ISSUE THREAD

**Issue by bgyori** [biopragmatics/bioregistry#569]
### Prefix

biomodels.kisao

### Explanation

The default resolver e.g., https://www.biomodels.net/kisao/KISAO#KISAO_0000057 doesn't work, but resolving to BioPortal or OLS does e.g., http://purl.bioontology.org/ontology/KISAO/kisao:KISAO_0000057 so one of those should be prioritized.

### Contributor ORCID

0000-0001-9439-5346

**Comment by bgyori** [comment]
As a side note, I find the prefix `biomodels.kisao` odd since KISAO can be considered a standalone resource, not a part of BioModels. It might make sense to change the prefix to just `kisao`.

**Comment by bgyori** [comment]
Further context: https://github.com/SED-ML/KiSAO#browsing-kisao, "KiSAO can be browsed through [BioPortal](https://bioportal.bioontology.org/ontologies/KISAO) and [OLS](https://www.ebi.ac.uk/ols/ontologies/kisao)."

**Comment by cthoyt** [comment]
Strange, this site used to work, since it's been manually overridden. I wonder what happened to it.

**Comment by bgyori** [comment]
My guess is the resource got moved out from BioModels and is now considered standalone.
