### ISSUE TITLE
vbo example URIs redirect to 500 page at Ontobee 

### ISSUE THREAD

**Issue by sierra-moxon** [biopragmatics/bioregistry#582]
### Prefix

vbo

### Explanation

This is a very new ontology so it could be that it has not yet percolated to Ontobee (nor OLS).  Until it does, the URIs on the Bioregistry page will result in 500 errors. 

Should the URIs be left blank if they result in 500 errors?  

### Contributor ORCID

0000-0002-8719-7760

**Comment by sierra-moxon** [comment]
https://github.com/monarch-initiative/vertebrate-breed-ontology/issues/29
[EBISPOT/OLS#636](https://github.com/EBISPOT/OLS/issues/636)
[OntoZoo/ontobee#183](https://github.com/OntoZoo/ontobee/issues/183)

**Comment by cthoyt** [comment]
This sounds like a OBO Library PURL issue more than Bioregistry, but since this is broken we could always override it directly in the Bioregistry

**Comment by cthoyt** [comment]
This has been fixed upstream
