### ISSUE TITLE
Send new prefix request for AEON

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#616]
Would be great if @StroemPhi could send a new prefix request for https://github.com/tibonto/aeon using this link: https://github.com/biopragmatics/bioregistry/issues/new?assignees=biopragmatics%2Fbioregistry-reviewers&labels=New%2CPrefix&template=new-prefix.yml&title=Add+prefix+AEON

**Comment by StroemPhi** [comment]
done in https://github.com/biopragmatics/bioregistry/issues/617
😉
