### ISSUE TITLE
Add prefix ARBA

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#620]
### Prefix

ARBA

### Name

Association-Rule-Based Annotator

### Homepage

https://www.uniprot.org/arba

### Repository

bioregistry

### Description

Association-Rule-Based Annotator (ARBA), a multiclass, self-training annotation system for automatic classification and annotation of UniProtKB proteins ([3](javascript:;)). This replaces the previous rule-based SAAS system.

### Example Local Unique Identifier

ARBA00000001

### Regular Expression Pattern for Local Unique Identifier

ARBA\d+

### URI Format String

https://www.uniprot.org/arba/$1

### Contributor Name

Chris Mungall

### Contributor GitHub

cmungall

### Contributor ORCiD

0000-0002-6601-2165

**Comment by cmungall** [comment]
yes it's a banana

**Comment by cthoyt** [comment]
@cmungall a couple pieces of feedback:

1. Was it unclear what was supposed to go in the `Repository` field based on what was written on the new issue form? This should have been a source code repository for the resource, but you wrote `bioregistry`, which doesn't really make sense
2. Prefixes must be lowercase
3. I'm going to change the canonical prefix to `uniprot.arba` to make it more explicit that it's in the uniprot universe but retain `arba` as a synonym
4. There's a long discussion about whether the redundant use of a prefix within a local unique identifier without a delimiter itself counts as a banana, so this one can stay. UniProt doesn't itself use a principled prefix system, so this is why they like to add this redundant information to make it possible to figure out what vocabulary a string is referring to
