### ISSUE TITLE
make namespace in pattern consistent for OBO

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#63]
See also #191

These have ns-in-pattern = False

http://bioregistry.io/registry/obi
http://bioregistry.io/registry/ecto
http://bioregistry.io/registry/fbbt
...

so the regex only covers the numeric part and the page shows:

```
Namespace in Pattern
False
Example Identifier
0000001
```

These have ns-in-pattern = True

http://bioregistry.io/registry/go
http://bioregistry.io/registry/cl
http://bioregistry.io/registry/uberon

and the regex covers the complete CURIE, and the page (correctly) shows example CURIEs

While technically it doesn't make a difference (other than I guess some performance impact with processing the regexes on large numbers of IDs), I think this should be normalized to True.

I think it's confusing to show OBO CURIEs having Example IDs having only numbers, e.g.

![image](https://user-images.githubusercontent.com/50745/119910010-0c7d0f00-bf0b-11eb-9f1a-9f51b02b4288.png)

I know the legacy of this, with the bioinformatics community being terrible at IDs and being inconsistent at what we mean by ID, ending up with the MGI:MGI issue, but at least within OBO we are clear and consistent, there is one canonical CURIE form, and one canonical URI.

**Comment by cthoyt** [comment]
I've addressed this by making several tweaks to the interface. 

1. The namespace embedded in LUI is now only discussed in the context of maintaining compatibility with MIRIAM (at least when it's self-consistent)
2. The word "identifier" is no longer used alone. Now it's listed as "local unique identifier" which I don't think anyone can argue against writing without the prefix.
3. There is now an example CURIE that shows what people are more likely expecting for OBO 

Screenshot from https://bioregistry.io/registry/chebi:

<img width="944" alt="Screen Shot 2022-01-05 at 12 47 34" src="https://user-images.githubusercontent.com/5069736/148212888-94ea9084-7da2-4b88-bede-796c59e012cb.png">
