### ISSUE TITLE
[Resource]: MOSAiC Ontology

### ISSUE THREAD

**Issue by caufieldjh** [biopragmatics/bioregistry#636]
### Prefix

mosaic

### Name

MOSAiC Ontology

### Homepage

https://bioportal.bioontology.org/ontologies/MOSAIC

### Repository

https://github.com/DataONEorg/sem-prov-ontologies

### Description

An ontology used to describe data resources in the Arctic Data Center (https://arcticdata.io).

### Example Local Unique Identifier

00005643

### URI Format String

https://purl.dataone.org/odo/MOSAIC_$1

### Contributor Name

Harry Caufield

### Contributor GitHub

caufieldjh

### Contributor ORCiD

0000-0001-5705-7831

### Contact Name

Bryce Mecum

### Contact Email

mecum@nceas.ucsb.edu

**Comment by cthoyt** [comment]
@caufieldjh are all of the identifiers 8 long left padded by zeros?

**Comment by caufieldjh** [comment]
Yes, that's consistent.

**Comment by cthoyt** [comment]
I’m afk right now but will merge this when I’m back. One thing that would be nice is if you could write a bit more of a detailed description.

**Comment by cthoyt** [comment]
Really interesting, I was reading through the contributors and found that @samanthacsik was involved. We went to Northeastern together in Boston!

**Comment by cthoyt** [comment]
FYI the nightly build failed last night because of some non-trivial redundancies. I fixed those this morning and the mosaic page is now live at https://bioregistry.io/registry/mosaic 🎸
