### ISSUE TITLE
Report misalignment from [Orphanet] 

### ISSUE THREAD

**Issue by sierra-moxon** [biopragmatics/bioregistry#646]
### Bioregistry Prefix

orphanet

### Metaprefix

I am not entirely sure what a metaprefix is, but I see "ORPHA:2131" on orphanet itself: https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=2131

### External Prefix

ORPHA

### Contributor ORCID

0000-0002-8719-7760

**Comment by cthoyt** [comment]
Hi Sierra, I just added this form today and you’re the first to use it! The idea was that if some of the mappings to external prefixes were wrong, you could use this form. Apparently it wasn’t very clear what this was for. 

Are you suggesting that there’s an issue with the bioregistry prefix being orphanet when they themselves use ORPHA?

**Comment by sierra-moxon** [comment]
Oh ok, I see.  Sorry about that!  Yes, I was trying to raise the issue of what to do when a resource uses one prefix locally and we don't have the same prefix in bioregistry.  `orphanet` is also used at identifiers.org.  I was hoping to have a brief discussion here to refer to in diverging from what I see on their site.

**Comment by cthoyt** [comment]
Keep in mind the point of the bioregistry is to provide an interoperability hub - empirically, it's very hard to convince people to use prefixes other than what they're comfortable with. To faciliate this, Nico and I have implemented the concept of "contexts" so you can encode deterministic rules for transforming the bioregistry for your use case (which could entail renaming some prefixes). 

See https://bioregistry.io/context/ for more information on this, and if you think it might be relevant, please let me know where are gaps in the information there so we can improve it for the next time you or someone else needs to refer to it
