### ISSUE TITLE
clingene vs. caid 

### ISSUE THREAD

**Issue by sierra-moxon** [biopragmatics/bioregistry#647]
### Prefix

clingene

### Explanation

ClinGen designates 'caid' (Canonical Allele Identifier) as a prefix for clinical allele identifiers:
https://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/by_caid?caid=CA358802

could we either rename the prefix `clingene` to `caid` or add `caid` as a synonym for `clingene` ?

https://www.youtube.com/watch?v=qDkeumpWqJo -- starting at 5:05 is helpful

### Contributor ORCID

0000-0002-8719-7760

**Comment by cthoyt** [comment]
Thanks @sierra-moxon, I added the appropriate synonym.
