### ISSUE TITLE
add TogoID as registry #BioHackEU22

### ISSUE THREAD

**Issue by egonw** [biopragmatics/bioregistry#649]
[TogoID](https://togoid.dbcls.jp/) (https://github.com/togoid) is a new ID mapping services and has an internal registry of datbases. Some alignment sounds appropriate.

I did not know which template to use for this, but if someone tells me, I'll update this issue with that template.

**Comment by cthoyt** [comment]
@egonw I just added some notes in the contribution guidelines on https://github.com/biopragmatics/bioregistry/blob/main/docs/CONTRIBUTING.md#adding-a-new-registry. You'll have to give some more information on TogoID, I think I remember reading the paper but not being super motivated to follow-up.

Ideally you can just convince them to align with Bioregistry and this would not be necessary :)

**Comment by cthoyt** [comment]
see structured registry at https://github.com/togoid/togoid-converter/blob/develop/swagger/swagger-config.yaml
