### ISSUE TITLE
OBO ontology "GEO" does not appear in bioregistry

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#67]
http://bioregistry.io/registry/geo

This (IMO, rightly) is the prefix for the Gene Expression Omnibus

This poses the question of where this should live in the registry:

http://obofoundry.org/ontology/geo

There may be an implicit understanding that due to its prominence in genomics, GEO should take precedence. Additionally, GEO is a major resource. However, these kinds of principles need to be articulated, and there should be some kind of process for appealing decisions etc.

**Comment by cthoyt** [comment]
Please see http://bioregistry.io/registry/geoeo. How have you gone about looking for entries? I need to improve the front page search to work on names and prefix synonyms too

**Comment by cthoyt** [comment]
The discussion about how conflicts are handled as well as other prefix policies is continuing in https://github.com/biopragmatics/bioregistry/issues/158, so I'm going to close this one
