### ISSUE TITLE
Update example, pattern, and URI format for MIXS

### ISSUE THREAD

**Issue by only1chunts** [biopragmatics/bioregistry#685]
### Prefix

MIXS

### Explanation

The information given here: https://bioregistry.io/registry/mixs is incorrect.
The unique ID for a MIXS term is its numerical identifier.
So for the example currently shown in that page "ph_regm" it should point to MIXS:0001056
I guess that means the regx is also wrong, but I dont know how to write regx. its just MIXS: followed by 7 digits (`^\\d{7}$`).
The ids resolve via w3id.org, e.g.
https://w3id.org/mixs/0001056
Documentation is available here: https://genomicsstandardsconsortium.github.io/mixs/introduction/background/

### Contributor ORCID

0000-0002-1335-0881

**Comment by cthoyt** [comment]
Thanks @only1chunts, we will take care of improving this and tag you on the PR for review.
