### ISSUE TITLE
Mention of Elixir node

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#711]
@egonw in https://github.com/BioSchemas/bioschemas.github.io/pull/728#issuecomment-1382871786 you mentioned that you would write bioregistry is attached to the Dutch elixir node because of your contributions and coauthorship. Is this something that we should include on the website/readme? Maybe you can explain a bit more how this works. I think people respond positively to elixir branding so this could be beneficial for the project

**Comment by egonw** [comment]
No, I don't think we can. Us using it for in ELIXIR (WikiPathways is an ELIXIR-NL service, and BridgeDb is an ELIXIR Recommended Interoperability Resources) may be enough to put the live deployment as related to ELIXIR-NL, but listing that on the Bioregistry website will likely give the impression Bioregistry itself is linked to ELIXIR (like a service).

You even make me rethink the node can even be mentioned on the live deploys page.

**Comment by cthoyt** [comment]
Okay, thanks for the clarification.

**Comment by cthoyt** [comment]
@egonw do you think you can educate me  about elixir interoperability resources and potentially help in getting the bioregistry listed as one? Does that even make sense?

**Comment by egonw** [comment]
I wish I could, but every country implements things differently. You should contact ELIXIR-DE: https://elixir-europe.org/about-us/who-we-are/nodes/germany
