### ISSUE TITLE
Update OMIA 

### ISSUE THREAD

**Issue by ImkeTammen** [biopragmatics/bioregistry#719]
### Prefix

OMIA

### Explanation

We would like to update information in relation to OMIA (Online Mendelian Inheritance in Animals) in the bioregistry. The website link has been changed in 2021. The current website link is: omia.org/ . The website is curated jointly by Frank Nicholas and myself (Imke Tammen). As Frank is retired we discussed that my name should be added as contributor: Orcid ID: 0000-0002-5520-6597, GitHub: ImkeTammen. Please let us know if any additional information is needed. Kind regards, Imke

### Contributor ORCID

0000-0002-5520-6597

**Comment by cthoyt** [comment]
Hi @ImkeTammen , this is great. I will make a PR to update this. However, we require getting the email address when listing contact persons. Can you please share the one you'd like to show?

**Comment by ImkeTammen** [comment]
Sorry for the delayed response and yes  imke.tammen@sydney.edu.au   is the best email.
