### ISSUE TITLE
Add prefix gear

### ISSUE THREAD

**Issue by jorvis** [biopragmatics/bioregistry#728]
### Prefix

gear

### Name

Gene Expression Analysis Resource

### Homepage

https://umgear.org

### Repository

bioregistry

### Description

The gEAR portal is a website for visualization and analysis of multi-omic data both in public and private domains. 

### License

AGPL-3.0-only	

### Example Local Unique Identifier

d.a59037e8

### Regular Expression Pattern for Local Unique Identifier

^[dp]\.[a-z0-9]{8}$

### URI Format String

https://umgear.org/p?id=$1

### Contributor Name

Joshua Orvis

### Contributor GitHub

jorvis

### Contributor ORCiD

0000-0002-5705-5710

### Contact Name

Joshua Orvis

### Contact ORCiD

0000-0002-5705-5710

### Contact GitHub

jorvis

### Contact Email

jorvis@gmail.com

### Additional Comments

Thanks for the suggestion!

**Comment by jorvis** [comment]
Great, thanks!

**Comment by cthoyt** [comment]
@jorvis https://bioregistry.io/gear is live!
