### ISSUE TITLE
Old style identifiers.org URLs not available in reverse prefix map

### ISSUE THREAD

**Issue by bgyori** [biopragmatics/bioregistry#730]
When creating a prefix map using

```python
bioregistry.manager.get_reverse_prefix_map(include_prefixes=True)
```
the keys include the following variants for identifiers.org, using the example of DOID below:
```
http://identifiers.org/DOID/
http://identifiers.org/DOID:
https://identifiers.org/DOID/
https://identifiers.org/DOID:
```

These do not include the "old style" identifiers.org URL prefix which would be
```
http://identifiers.org/doid/DOID:
```

These kinds of URLs are used in the wild and I found that when doing 
```python
converter = curies.Converter.from_reverse_prefix_map(bioregistry.manager.get_reverse_prefix_map(include_prefixes=True))
converter.parse_uri('http://identifiers.org/doid/DOID:0080600')
```
I get `('idot', 'doid/DOID:0080600')` rather than `('doid', '0080600')`.

**Comment by cthoyt** [comment]
Do you think this style only applies when there's a namespace embedded in LUI, or should be applied to all namespaces?

**Comment by bgyori** [comment]
It's a general pattern that used to apply to all namespaces before they switched to CURIEs. See e.g., http://identifiers.org/fplx/ERK.

**Comment by cthoyt** [comment]
Noting that the following two do not work:
- https://identifiers.org/fplx/fplx:ERK (does not have namespace embedded in lui)
- http://identifiers.org/ChEBI/138488 (does have namespace embedded in lui)

Despite the correctness/incorrectness of these, I'm still wondering if it's a good idea to include these in the reverse prefix map so in case someone who also misinterpreted what's allowed created some references, they might still be reconcilabile
