### ISSUE TITLE
Logo link broken in metaregistry

### ISSUE THREAD

**Issue by bgyori** [biopragmatics/bioregistry#731]
This link https://github.com/biopragmatics/bioregistry/blob/main/src/bioregistry/data/metaregistry.json#L791 doesn't work currently. Would this one be the right replacement: http://identifiers.org/identifiers_logo.f6737b08.png?

**Comment by cthoyt** [comment]
Thanks for the heads up. It's very weird they have something like a hash in the name, such that it changes.
