### ISSUE TITLE
Change resolver for ecocyc from biocyc.org to ecocyc.org

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#737]
Current:

https://biocyc.org/gene?id=AICARTRANSIMPCYCLO-CPLX

Proposed change to:

https://ecocyc.org/gene?id=AICARTRANSIMPCYCLO-CPLX

While the former should resolve to the latter, the behavior is dependent on whether you are logged on, your current biocyc license, and the amount of times you have accessed the site. If you have accessed too often and don't have a license then the former will be a dead end.

**Comment by cthoyt** [comment]
Which prefix is this for?

**Comment by cthoyt** [comment]
oh i see now in the title... are you aware there are issue templates for these?
