### ISSUE TITLE
Update OPB resolver

### ISSUE THREAD

**Issue by bgyori** [biopragmatics/bioregistry#767]
### Prefix

opb

### Explanation

Currently, when resolving https://bioregistry.io/opb:01625, Bioregistry goes to

https://bioportal.bioontology.org/ontologies/OPB?p=classes&conceptid=http%253A%252F%252Fbhi.washington.edu%252FOPB%2523OPB_01625

which does not work. When manually navigating BioPortal, the following is the correct link:

https://bioportal.bioontology.org/ontologies/OPB/?p=classes&conceptid=http%3A%2F%2Fbhi.washington.edu%2FOPB%23OPB_01625

### Contributor ORCID

0000-0001-9439-5346

**Comment by cthoyt** [comment]
There is a massive heterogeneity in opb - can you check some other uris? They don’t all follow the same format from what I can see

**Comment by cthoyt** [comment]
@bgyori I'm sorry, I mixed this up with IOBC. Will send a fix now!
