### ISSUE TITLE
Add ontolgies from NFDI4chem list

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#781]
NFDI4Chem is an initiative to build an open and FAIR infrastructure for research data management in chemistry, supported by the German Chemical Society, German Bunsen Society for Physical Chemistry, and German Pharmaceutical Society.

They've created a list of relevant ontologies in https://nfdi4cat.org/services/ontologie-sammlung/

**Goal:** Add any ontologies with sufficient quality and metadata availability that are missing from the Bioregistry.

**Comment by cmungall** [comment]
do you know if the registry is available as a yaml/tsv? I'd like to include these in the semantic-sql registry too.

One thing I could do is use bioregistry as the SSoT for non-OBO ontology download URLs, etc

https://github.com/biopragmatics/bioregistry/pull/782/files#diff-fc2d7cf2a3f3627fc681401567c31c130c43ad03a67d2ee4be5023795f354909

but that feels a little like scope creep?

**Comment by cthoyt** [comment]
@cmungall the list that this PR is referring to is very informal, and after chatting with @StroemPhi, doesn't necessarily reflect the reality of the NFDI4Chem project. A better place to look is https://terminology.tib.eu/ts/collections, which is built with the OLS as a backend and a custom front-end.

I am already using the Bioregistry as a SSoT for non-OBO ontology download URLs myself. I think this is well within the scope of the Bioregistry. For example, I use it in https://github.com/cthoyt/oquat to make assessments over all available ontologies.

One thing I haven't done with Bioregistry is to annotate the ontology dumps I made in https://github.com/biopragmatics/obo-db-ingest, but that could also potentially be useful

**Comment by StroemPhi** [comment]
Just for the records, the list provided in the description here is from NFDI4Cat, which is the NFDI consortium for catalysis, not NFDI4Chem ;) 
AFAIK their still in the analysis phase to find out which of these ontologies to recommend for reuse and model their first own ontology prototypes. They might also have their own terminology service / lookup service sometime soon.
