### ISSUE TITLE
Update BARTOC registry

### ISSUE THREAD

**Issue by nichtich** [biopragmatics/bioregistry#783]
### Prefix

bartoc

### Explanation

The information at https://bioregistry.io/registry/bartoc is outdated. Andreas Ledl is still affiliated with the project but not as main contact. Contact could be https://orcid.org/0000-0002-7613-4123 or even better no individual but the organization https://ror.org/048vdhs48 (or both).

I would have done  a pull request, but the main data `src/bioregistry/data/metaregistry.json` seems to be duplicated in `export/` and I don't want to change in three places or locally clone the repository and install toolkit to do so automatically.

### Contributor ORCID

0000-0002-7613-4123

**Comment by cthoyt** [comment]
Thanks @nichtich  - the policy on Bioregistry is to have exactly one contact person for each resource, however we also annotate organizations as well via ROR, so I can take care of both of those. Can you share an email that's appropriate for contacting you?
