### ISSUE TITLE
Broader support for use_preferred in CURIE/prefix normalization

### ISSUE THREAD

**Issue by dhimmel** [biopragmatics/bioregistry#790]
https://github.com/biopragmatics/bioregistry/pull/483 introduced a `use_preferred` argument for `curie_from_iri` which instructs the returned CURIE to use preferred prefix capitalization.

Should `use_preferred` exist for more functions like:

- `normalize_curie`
- `normalize_prefix`
- `normalize_parsed_curie`

Separately, I wonder if `use_preferred` should use UPPERCASE for prefixes without a preferred form, given that this seems more common in the wild?

Take for example the following use case: I want to go through every xref in EFO and normalize them to remove any polymorphic prefixes. Lowercasing all the prefixes would probably be rejected, but use_preferred might be accepted.

**Comment by dhimmel** [comment]
Perhaps it's worth thinking about the possible flavors of normalized prefixes:

- lower
- upper
- preferred or lower
- preferred or upper

**Comment by bgyori** [comment]
I like these ideas as features in Bioregistry to allow for more options in prefix normalization. However, I'm not sure about changes to EFO's existing xrefs: any change, even if appropriate might not be accepted because it breaks existing assumptions about the sytling of xref CURIEs, and also, assuming you're using Bioregistry to consume xref CURIEs, as long as the CURIEs there can be interpreted, they don't need to be standardized to begin with. What do you think?

**Comment by dhimmel** [comment]
> I'm not sure about changes to EFO's existing xrefs

That was mostly a hypothetical, although I do think ontologies should pick a standard prefix for each resource and apply it consistently across their entire xref corpus. But having that discussion here is a digression! So we'll keep this issue just about what Bioregistry should support.

**Comment by cthoyt** [comment]
In #791, I added the ability to pass `use_preferred` to several functions, while simultaneously streamlining their implementations.

However, I'm not sure adding additional complexity and implicitly encouraging creating different variants of the canonical prefixes is a good idea. In a perfect world, all data would be be standardized to Bioregistry canonical prefixes (which throw away distracting information like casing) and then optionally displayed according to the preferred prefix field (only when a preferred capitalization variant explicitly annotated, which usually is only from the identifier space owner). Making it easier to get at those preferred prefixes has been an often-requested feature, so I think the changes implemented in #791 are a reasonable compromise.

I don't think enabling making additional casing variants is something we want to encourage by implementing. Depending on your use case, is it sufficient to apply simple string transformations when you need them? Perhaps you could describe in a bit more detail what you're trying to do - I might have missed the main point here.

**Comment by dhimmel** [comment]
> I added the ability to pass `use_preferred` to several functions, while simultaneously streamlining their implementations.

Nice. That's sufficient to close this issue.

> Perhaps you could describe in a bit more detail what you're trying to do

For resources where `namespace_in_lui` (namespace embedded in local unique identifier), the identifier might be invalidated by deviating from the preferred prefix capitalization. Should `use_preferred=True` address this issue?

My larger motivation here was primarily for situations where a bunch of CURIEs are encountered from a resource. For example, cross-references in an ontology like EFO. I want to clean up all the polymorphic prefixes, but want to retain the EFO-preferred capitalization of prefixes (which may not be documented anywhere).

**Comment by bgyori** [comment]
There is a dedicated way to check for `namespace_in_lui` (also called `banana` by @cthoyt) where the namespace is handled in the way you would expect. Take a look at these functions: https://github.com/biopragmatics/bioregistry/blob/main/src/bioregistry/schema/struct.py#L798-L893. Here, we have `get_pattern`, and `get_pattern_with_banana`, the latter producing a patter which allows checking for `namespace_in_lui` for namespaces where that can be used.

This piece of code I have in one downstream application can also be helpful:

```python
    registry = load_resource_json('bioregistry.json')
    for prefix, entry in registry.items():
        # If there is a pattern we make a pre-compiled version of it
        # for faster matching.
        if 'pattern' in entry:
            pattern = entry['pattern']
            # If there is a banana, we need to add it to the pattern
            if 'banana' in entry:
                banana_peel = entry.get('banana_peel', ':')
                pattern = '^%s%s%s' % (entry['banana'],
                                       banana_peel,
                                       pattern[1:] if pattern.startswith('^')
                                       else pattern)
            entry['pattern_compiled'] = re.compile(pattern)
```

**Comment by cthoyt** [comment]
Great, I will close this but feel free to continue discussion or make a new issue

**Comment by dhimmel** [comment]
> There is a dedicated way to check for `namespace_in_lui` (also called `banana` by @cthoyt)

Hmm. I don't understand banana. So putting docs here:

https://github.com/biopragmatics/bioregistry/blob/fb8c26a2d4d5900fc55ca11b6b463ddd6d350dce/src/bioregistry/schema/struct.py#L439-L445

https://github.com/biopragmatics/bioregistry/blob/fb8c26a2d4d5900fc55ca11b6b463ddd6d350dce/src/bioregistry/schema/struct.py#L375-L388

So `namespace_in_lui` is a bool, while `banana` is a str allowing for an embedded namespace that differs from the preferred prefix.

Permalinking "[these functions](https://github.com/biopragmatics/bioregistry/blob/fb8c26a2d4d5900fc55ca11b6b463ddd6d350dce/src/bioregistry/schema/struct.py#L798-L893)" that include `get_pattern_with_banana`.
