### ISSUE TITLE
Add prefix demo

### ISSUE THREAD

**Issue by pfabry** [biopragmatics/bioregistry#808]
### Prefix

demo

### Name

DEMographics Ontology

### Homepage

https://openlhs.github.io/DEMO/

### Repository

https://github.com/OpenLHS/DEMO

### Description

DEMO is an ontology of informational entities about demographic data in a context of Learning Health System.

### License

CC-BY-4.0

### Example Local Unique Identifier

0000001

### Regular Expression Pattern for Local Unique Identifier

^\d{7}$

### Contributor Name

Paul Fabry

### Contributor GitHub

pfabry

### Contributor ORCiD

0000-0002-3336-2476

### Contact Name

Paul Fabry

### Contact ORCiD

0000-0002-3336-2476

### Contact GitHub

pfabry

### Contact Email

paul.fabry@usherbrooke.ca

**Comment by pfabry** [comment]
This prefix is not needed for now. A new issue with another prefix will be created when necessary.

**Comment by cthoyt** [comment]
thanks @pfabry ! Sorry the turnover was slow on the other ones. Let me know if there's anything else I can do to support you
