### ISSUE TITLE
WikiPathways ontology and database confused

### ISSUE THREAD

**Issue by egonw** [biopragmatics/bioregistry#818]
### Prefix

wikipathways

### Explanation

WikiPathways has an ontology (in OLS, BioPortal, AberOWL) and is a databases. They are separate.

However, the current WikiPathways record combines the two: https://bioregistry.io/registry/wikipathways

That is not correct. But I am not sure how this should be fixed.

### Contributor ORCID

0000-0001-7542-0286

**Comment by cthoyt** [comment]
Example page: https://bioportal.bioontology.org/ontologies/WIKIPATHWAYS/?p=classes&conceptid=http%3A%2F%2Fvocabularies.wikipathways.org%2Fwp%23DataNode

so this is a distinct semantic space from wikipathways itself. @egonw what do you think would be the best prefix for this? You can not have `wp` within Bioregistry, it is a policy not to create two nor three letter prefixes as the collision  possibility is very high. Maybe `wikipathwayso`?

**Comment by egonw** [comment]
I will bring this up in the next telcon.

**Comment by cthoyt** [comment]
Great. In the mean time, I will add a new prefix to help mediate this, so we can fix the incorrect cross-references from bioportal, aberowl, and ols

**Comment by cthoyt** [comment]
See http://bioregistry.io/wikidata.vocab for the first attempt

**Comment by egonw** [comment]
@cthoyt, we were all happy with `wikipathways.vocab`.

**Comment by cthoyt** [comment]
Great, then we can call this one closed. Maybe there are some direct improvements to that namespace you can suggest in a different issue

**Comment by egonw** [comment]
I was just about the create a PR. Generally, it looks fine :)
