### ISSUE TITLE
Add prefix adcad

### ISSUE THREAD

**Issue by caufieldjh** [biopragmatics/bioregistry#827]
### Prefix

adcad

### Name

Arctic Data Center Academic Disciplines Ontology

### Homepage

https://arcticdata.io/

### Repository

https://github.com/NCEAS/adc-disciplines

### Description

An ontology to support disciplinary annotation of Arctic Data Center datasets.

### License

CC-BY 4.0

### Example Local Unique Identifier

odo:ADCAD_00000

### Contributor Name

Harry Caufield

### Contributor GitHub

caufieldjh

### Contributor ORCiD

0000-0001-5705-7831

### Contact Name

Bryce Mecum

### Contact GitHub

amoeba

### Contact Email

mecum@nceas.ucsb.edu

**Comment by cthoyt** [comment]
@caufieldjh thanks! Will take care of this first thing tomorrow. However in your example local unique identifier this is obviously a curie that further contains a banana. Was this on purpose?

**Comment by caufieldjh** [comment]
Yep, that's redundant and unintentional.
Local id should be more like `00000`

**Comment by cthoyt** [comment]
Thanks for the clarification. You can see the other updates I made in the PR - for example, I looked inside the RDF file to figure out what the URI format string was.

Also, it appears that there are a few other ontologies from this project listed at https://github.com/DataONEorg/dataone_purl/blob/master/conf/01-ontologies.conf. Mosaic is already in bioregistry, but the others are not. Maybe you want to add the others?

**Comment by caufieldjh** [comment]
Good idea - I see you just added the others 🙂
