### ISSUE TITLE
Update URLs in the registry for epd

### ISSUE THREAD

**Issue by smoretti** [biopragmatics/bioregistry#831]
### Prefix

epd

### Explanation

The EPD resource is moving, so URLs have changed:

- the homepage is now: https://epd.expasy.org/epd/
- the resolved URI is now: https://epd.expasy.org/cgi-bin/epd/query_result.pl?out_format=NICE&Entry_0=TA_H3

Thanks

### Contributor ORCID

0000-0003-3947-488X

**Comment by cthoyt** [comment]
hey @smoretti I troll the identifiers.org issue tracker so I actually already made this update for you in #830 :)

**Comment by smoretti** [comment]
Thanks

**Comment by cthoyt** [comment]
@smoretti given the Bioregistry has a more detailed data model than Identifiers.org, is there anything else you would like improved on https://bioregistry.io/registry/epd?

For example, is Philipp Bucher still the correct contact person? Do you have their GitHub handle / ORCID / email address? Is there an issue tracker we can link to in case people have questions?

**Comment by smoretti** [comment]
Philipp Bucher is still the contact person. His email is <Philipp.Bucher@sib.swiss>

**Comment by smoretti** [comment]
Sorry, in fact the current email - ask-epd@googlegroups.com - is better

**Comment by cthoyt** [comment]
It's actually Bioregistry policy to have single point of contact and not email lists - this is based off of the OBO principle for [locus of authority](https://obofoundry.org/principles/fp-011-locus-of-authority.html) which makes projects more accountable.
