### ISSUE TITLE
Add prefix NOYO

### ISSUE THREAD

**Issue by pfabry** [biopragmatics/bioregistry#838]
### Prefix

noyo

### Name

Groupe de Recherche Interdiscplinaire en Informatique de la Santé (GRIIS) Core ontology

### Homepage

https://openlhs.github.io/NOYO/

### Repository

https://github.com/OpenLHS/NOYO

### Description

The [GRIIS learning health system platform]( https://griis.ca/en/solutions/pars3/) is a a platform designed to support clinicians and researchers who conduct projects that require to access data stored in multiple, distributed systems. This platform relies on an ontological model of clinical information constituted of several domain-specific ontologies such as [PDRO]( http://obofoundry.org/ontology/pdro.html) or [LABO]( http://obofoundry.org/ontology/labo.html).
At the core of this model, NOYO (from “noyau” that means “core” in french) is an ontology including all core classes and properties, including those from external ontologies, used in downstream domain ontologies.

### License

CC-BY-4.0

### Example Local Unique Identifier

0000001

### Regular Expression Pattern for Local Unique Identifier

^\d{7}$

### Contributor Name

Paul Fabry

### Contributor GitHub

pfabry

### Contributor ORCiD

0000-0002-3336-2476

### Contact Name

Paul Fabry

### Contact ORCiD

0000-0002-3336-2476

### Contact GitHub

pfabry

### Contact Email

paul.fabry@usherbrooke.ca

**Comment by cthoyt** [comment]
Hi @pfabry , if you open up the OWL file, you can find the URI format string

<img width="1337" alt="Screenshot 2023-05-15 at 17 11 51" src="https://github.com/biopragmatics/bioregistry/assets/5069736/1c5377ec-87d8-4e7a-ab08-3fc7df400726">


Give an example IRI is http://purl.obolibrary.org/obo/NOYO_0000033, you just have to replace the local unique identifier (the number part) with `$1`. So you get ` http://purl.obolibrary.org/obo/NOYO_$1`

**Comment by pfabry** [comment]
Hi @cthoyt 
Thanks for the comment. I'll get it done for the next one :)

**Comment by cthoyt** [comment]
@pfabry A few ways to improve the description:

- it's not obvious from this where the acronym NOYO comes from mentions of other resources could be linked with markdown (at least written out in full)
- most importantly, I don't think that this description gives enough context as to what this is and what's going on other than mention of clinical information. How is this related to other resources that exist? Why should I use this semantic space instead of others? What is GRIIS learning health system platform?

**Comment by pfabry** [comment]
I'm closing the issue as we are in the process of determining a new, more official name for this ontology.
