### ISSUE TITLE
Ontology metadata?

### ISSUE THREAD

**Issue by udp** [biopragmatics/bioregistry#840]
We are using https://raw.githubusercontent.com/biopragmatics/bioregistry/main/exports/registry/registry.json in OLS to resolve CURIEs in ontologies.

However, I think it is unclear whether `uri_format` is the format for a <u>URL</u> from which the resource can be obtained; the format for the <u>ontology IRI</u> of the resource; or both.

For example, for GO, the registry provides:

    "uri_format": "http://amigo.geneontology.org/amigo/term/GO:$1",

which is great if I want to make a GO curie clickable. But if I want to resolve the GO CURIE to the IRI in the ontology, I would instead want to know the official OWL prefix which is `http://purl.obolibrary.org/obo/GO_`.

My current thinking is

1. `uri_format` should actually be `url_format`, because it specifically describes _locations_ at which the resource can be accessed. "uri" is still technically correct but I think you can be more specific here which would make it clear this is should not be used as an ontology IRI.

2. Where a resource is/has an ontology/ontologies, a new section like `ontologies: [...]` should be added providing links to the OWL files, the IRI prefix, and any other ontology-specific metadata which may be pertinent.

I am also not convinced this isn't completely out of scope for the bioregistry :D For example, the OBO foundry config provides this kind of metadata for all OBO ontologies, and OLS provides it for others.

However in this case I'm still not sure how to map between bioregistry<->ontologies in OBO/OLS.

**Comment by cthoyt** [comment]
@udp can we call this done?

**Comment by cthoyt** [comment]
Closing since no response @udp
