### ISSUE TITLE
Add prefix ott

### ISSUE THREAD

**Issue by caufieldjh** [biopragmatics/bioregistry#850]
### Prefix

ott

### Name

Open Tree of Life

### Homepage

https://tree.opentreeoflife.org/about/open-tree-of-life

### Repository

https://github.com/OpenTreeOfLife/

### Description

A tree of life constructed by combining published phylogenetic trees and taxonomic data. These identifiers refer to the Open Tree of Life reference taxonomy (OTT).

### Example Local Unique Identifier

4787619

### URI Format String

https://tree.opentreeoflife.org/taxonomy/browse?id=$1

### Contributor Name

Harry Caufield

### Contributor GitHub

caufieldjh

### Contributor ORCiD

0000-0001-5705-7831

### Additional Comments

Not sure who the contact should be - see https://tree.opentreeoflife.org/contact

**Comment by cthoyt** [comment]
I think we can pick a better prefix that’s longer than 3 letters. Also, can you help me understand all of these tree of life vocabularies? The names are very similar. Maybe we can make a joint push to include several more biodiversity prefixes together (usually it’s just not clear what prefix to give)

**Comment by cthoyt** [comment]
@caufieldjh can you please check https://bioregistry.io/registry/otol and confirm this is the same?

**Comment by caufieldjh** [comment]
OTOL and OTT aren't strictly the same: OTT is the reference taxonomy (https://tree.opentreeoflife.org/about/taxonomy-version/) and OTOL is the overall synthetic tree / the whole project - the difference being that various nodes on the synthetic tree either have specific ids corresponding to OTT ids (e.g., `ott5246890`, which directly corresponds to `OTT:5246890` in the taxonomy) or combined tree ids (like `mrcaott50ott3311`).

So if anything the `otol` prefix should be `ott` - taxon ids in this project will use that prefix as will external projects (since OTOL: won't really resolve to anything)

Maybe `ott3` or `otol.ott`?
