### ISSUE TITLE
Add prefix JGI

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#853]
### Prefix

jgi.proposal

### Name

Joint Genome Institute Proposals

### Homepage

https://genome.jgi.doe.gov/portal/

### Description

Identifiers for proposals/projects at the Joint Genome Institute

### Example Local Unique Identifier

502930

### Regular Expression Pattern for Local Unique Identifier

^\d+

### URI Format String

https://genome.jgi.doe.gov/portal/lookup?keyName=proposalId&groupOnly=1&app=Info&keyValue=$1

### Contributor Name

Chris Mungall

### Contributor GitHub

cmungall

### Contributor ORCiD

0000-0002-6601-2165

### Contact Name

Steven Wilson

### Contact ORCiD

0000-0002-8489-208X

### Contact Email

Steven Wilson

**Comment by cthoyt** [comment]
@cmungall @aclum can you please give a contact email for Steven Wilson?

**Comment by aclum** [comment]
Yes, sewilson@lbl.gov is correct.
