### ISSUE TITLE
Add new ontology collection for AIO

### ISSUE THREAD

**Issue by lnanderson** [biopragmatics/bioregistry#883]
## Title

> The Artificial Intelligence Ontology

## Description

> This ontology models classes and relationships describing deep learning networks, their component layers and activation functions, as well as potential biases.

## Keywords

> machine learning, artificial intelligence, computational methods, deep learning, neural networks

## Prefixes

> Prefix: aio, Preferred Prefix: AIO

## Author Name

> [Marcin Pawel Joachimiak](mailto:MJoachimiak@lbl.gov)

## Author ORCID Identifier

> [0000-0001-8175-045X](https://orcid.org/0000-0001-8175-045X)

## Links

> [Homepage](https://github.com/berkeleybop/artificial-intelligence-ontology)

## Metaregistry > Artificial Intelligence Ontology

> [Bioportal](https://bioportal.bioontology.org/ontologies/AIO), [FAIRsharing](https://doi.org/10.25504/FAIRsharing.8d6247), [OBO Foundary](http://obofoundry.org/ontology/aio)

## Identifier Schema

> [w3id.org](https://w3id.org/)

**Comment by bgyori** [comment]
Hi @lnanderson, thanks! Unless I'm mistaken, I think this resource would be a new prefix (i.e. a specific identifiers resource) rather than a new collection (a set of identifier resources provided by some organization). Would it make sense to submit a new issue using the new prefix template?

**Comment by lnanderson** [comment]
Hi @bgyori, new prefix does make more sense, my apologies for the oversight. I will create a new issue and you can close this one.
