### ISSUE TITLE
Remove no longer available entries

### ISSUE THREAD

**Issue by smoretti** [biopragmatics/bioregistry#889]
### Prefix

bgee.family

### Explanation

Hi
could you remove the following entries from bioregistry.io?

- bgee.family
- bgee.organ
- bgee.stage

The current version (and few last ones) of the Bgee database does not provide family, organ and stage pages any more.

Thanks

### Contributor ORCID

0000-0003-3947-488X

**Comment by cthoyt** [comment]
We can mark these as deprecated, but there may be data that exists somewhere that is tagged with these so we won't remove them.

**Comment by smoretti** [comment]
OK, thanks
