### ISSUE TITLE
Update the bgee.gene entry

### ISSUE THREAD

**Issue by smoretti** [biopragmatics/bioregistry#890]
### Prefix

bgee.gene

### Explanation

Hi

could you update the bgee.gene entry?

The **description** is now:
`Bgee is a database to retrieve and compare gene expression patterns in multiple species, produced from multiple data types (bulk RNA-Seq, scRNA-Seq, Affymetrix, in situ hybridization, and EST data). This collection references genes in Bgee.`

The **Pattern for Local Unique Identifiers** is now:
`^[A-Za-z0-9]+$`

The **URI** is now:
`https://www.bgee.org/gene/{$id}/`

The **Homepage** is now:
`https://www.bgee.org/`

The **Contact** is now:
`Bgee@sib.swiss`

Thanks

### Contributor ORCID

0000-0003-3947-488X

**Comment by cthoyt** [comment]
Thanks @smoretti. Just so you know, it's bioregistry policy to curate explicitly single person point of contact instead of group email addresses, so I've added your information for the contact person. If there's a different person you think is a better fit, please let me know.
