### ISSUE TITLE
No version specifier on pydantic breaks downstream packages

### ISSUE THREAD

**Issue by sneakers-the-rat** [biopragmatics/bioregistry#899]
The `setup.cfg` file lists a number of dependencies without version specifiers, this is generally a bad practice as it doesn't protect against breaking changes in newer versions or missing functionality in older versions.

In particular, the pydantic dependency is breaking downstream packages since v2.0 removed `pydantic.json.ENCODERS_BY_TYPE` so this import fails https://github.com/biopragmatics/bioregistry/blob/e87512b8a3c6c3b3193a7083a90acb32b0de86df/src/bioregistry/utils.py#L25C2-L25C2 .

It now exists in `pydantic.v1.json` https://github.com/pydantic/pydantic/blob/15d5e0b0abdd79fd63d34954e8dacaa9f1a255f8/pydantic/v1/json.py#L44

Unfortunately it looks like a number of downstream packages have pinned old versions of `bioregistry` so the damage is probably already done there, but to minimize similar problems i strongly recommend pinning versions that at least exclude new major semver updates until you can run tests and confirm the new versions work.

Downstream packages can fix this by manually pinning `poetry<2.0` but that's sort of a hack.

**Comment by cthoyt** [comment]
Do you know if there is a solution that will be compatible with both versions of pydantic? E.g.,

```python
try:
    from pydantic.v1.json import ENCODERS_BY_TYPE
except ImportError:
    from pydantic.json import ENCODERS_BY_TYPE
```

**Comment by cthoyt** [comment]
I read a bit and realized it's a big commitment to move to pydantic 2. This is not going to happen in the short term so [451c878](https://github.com/biopragmatics/bioregistry/commit/451c8781aa77e1ff8e8f5765e8ee63c192d09168) will call this closed. Thanks @sneakers-the-rat for pointing this out, it looks like we will have quite a bit to address

**Comment by sneakers-the-rat** [comment]
talked to some packaging folks about this - they suggested your best bet was to issue post releases for the back versions with a <2 upper limit

**Comment by dhimmel** [comment]
Was using an old version of bioregistry without 451c8781aa77e1ff8e8f5765e8ee63c192d09168 and hit this issue. Will subscribe to this issue, because I'm curious what the eventual best solution will be... trying to support pydantic 1 and 2 or making a clean upgrade to 2 and dropping support for 1.

**Comment by cthoyt** [comment]
I don't think it's possible to support both together. Making a clean upgrade to 2 will break everyone who is relying on this, so it will need a lot of communication and to make a new version update.

**Comment by dhimmel** [comment]
FastAPI is [supporting](https://twitter.com/dhimmel/status/1678449538242076673) both, but not saying its worth the effort. Not urging an upgrade anytime soon. I'm interested in the improved speed of pydantic v2, but `bioregistry` is just one of many dependencies that don't yet support pydantic v2. Seems like pydantic v1 versus v2 is going to fracture the python ecosystem like the Python 2/3 upgrade did 😨 .

**Comment by sneakers-the-rat** [comment]
> talked to some packaging folks about this - they suggested your best bet was to issue post releases for the back versions with a <2 upper limit

reiterating this - for old/present versions, you can just issue a [`.postN` release](https://peps.python.org/pep-0440/#post-releases) that has a `pydantic<2` requirement, and then future releases with a `pydantic^2` dependency will be able to signal to downstream packages that they need to pin the last version that depends on `<2`

**Comment by cmungall** [comment]
Provided you don't use too many pydantic features, supporting both might only be a matter of:

```python
try:
    from pydantic.v1 import <...>
except ImportError:
    from pydantic import <...>
```

- json encoders in utils.py - is this really required?
- fields not explicitly declared Optional in struct.py - this should be done anyway regardless of v1 vs v2 changes
- use of regex rather than pattern in struct.py - hmm, this one will be more annoying to fix

**Comment by manulera** [comment]
This affects schema-automator: https://github.com/linkml/schema-automator/issues/120

**Comment by cthoyt** [comment]
@manulera Bioregistry has since been made to explicitly support pydantic 1 and 2, can you please elaborate on what the issue is?
