### ISSUE TITLE
GOCHE: the case for prefix management in the case of squatting

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#909]
[GOCHE](https://bioregistry.io/registry/goche) (GO Chemicals) is an interesting case for bioregistry as it:

1. Is using an OBO PURL in the released GO ontology
2. Does not have the permission to do so

See also https://github.com/geneontology/go-ontology/issues/19535

I would personally like it if we go with 1, and add the currently used OBO purl to the GOCHE metadata record. Any objections?

**Comment by cthoyt** [comment]
See https://cthoyt.com/2023/03/11/obolibrary-masquerade.html for more detailed analysis of OBO PURL squatting

**Comment by cthoyt** [comment]
Even if it's not following OBO rules, if people are using fake OBO PURLs in the wild, it's worth noting it in the bioregistry. this has been done in many places

**Comment by matentzn** [comment]
Fantastic analysis! Sorry I missed it the first time around!

**Comment by matentzn** [comment]
(Can you give me some kind of rights on this repo so I can assign myself issues?)

**Comment by cthoyt** [comment]
@matentzn what kind of follow-up do you want to do on this?

**Comment by matentzn** [comment]
I think this is a reasonable process:

1. checking bioregistry for prefix clashes in now mandatory in OBO
2. Since goche is in there, no new ontology can assume this prefix
3. PURL may not be official, and not supported by OBO, but there wont be a clash because of the above

IMO this is enough! Case closed.
