### ISSUE TITLE
Issue with gogo resolution

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#93]
both don't work:
https://bioregistry.io/go:go:0048285 
https://bioregistry.io/go:GO:0048285

**Comment by cmungall** [comment]
Should they? The correct CURIE is GO:0048285

**Comment by cthoyt** [comment]
That's a nice philosophical question. They probably shouldn't, but I want to support this pattern to save anyone who does naive concatenation of a prefix (whether a standardized one like `go` or one with a community-specific flavor like `GO`) and an identifier that might or might not have a redundant prefix in it

**Comment by cthoyt** [comment]
This works now, regardless of whether this is correct
