### ISSUE TITLE
Add provider for [SMILES]

### ISSUE THREAD

**Issue by NishaSharma14** [biopragmatics/bioregistry#931]
### Prefix

CMS

### URI Format String

https://api.naturalproducts.net/latest/chem/descriptors?smiles=$1&format=json&toolkit=rdkit

### Contributor ORCID

0000-0002-2564-3243

**Comment by cthoyt** [comment]
Hi @NishaSharma14, sorry I didn't open a PR with discussion for this, but it was a pretty straightforward change you can see in https://github.com/biopragmatics/bioregistry/commit/37af4d56a5454d019b0f74dfa7b516f6b4537929. I think you will also want to make additional provider requests for SMILES as well as InChI/InChI-Key for other endpoints, so we can do a larger PR for those.
