### ISSUE TITLE
Minimal Information about any Sequence Homepage URL Updates

### ISSUE THREAD

**Issue by lnanderson** [biopragmatics/bioregistry#947]
### Prefix

mixs

### Explanation

The [MIxS registry](https://bioregistry.io/registry/mixs) selected Homepage URL is broken. The following error is displayed when redirected "Error 404 page not found". Below the relevant URLs for this issue.

- Current URL: https://gensc.org/mixs/ (broken)
- Suggested URL: https://www.gensc.org/pages/standards/all-terms.html (updates)
  - Related URL: https://genomicsstandardsconsortium.github.io/mixs/

### Contributor ORCID

0000-0002-8741-7823

**Comment by lnanderson** [comment]
@cthoyt quick homepage URL update.

**Comment by cthoyt** [comment]
Thanks!
