### ISSUE TITLE
Add prefix voc4cat

### ISSUE THREAD

**Issue by dalito** [biopragmatics/bioregistry#957]
### Prefix

voc4cat

### Name

voc4cat - A vocabulary for the catalysis disciplines

### Homepage

https://nfdi4cat.github.io/voc4cat/

### Repository

https://github.com/nfdi4cat/voc4cat

### Description

Voc4Cat is a [SKOS](https://www.w3.org/TR/2009/REC-skos-reference-20090818/) vocabulary for the catalysis disciplines. The vocabulary was created in the [NFDI4Cat](http://www.nfdi4cat.org/) initiative. The first collection of terms was published in June 2023 with a focus on photo catalysis. Our goal is to continuously extend the vocabulary to other areas of catalysis and related disciplines like chemical engineering or materials science.

### License

CC0

### Example Local Unique Identifier

0000123

### Regular Expression Pattern for Local Unique Identifier

^$https://w3id.org/nfdi4cat/voc4cat_([0-9]{7,})

### URI Format String

https://w3id.org/nfdi4cat/voc4cat_0000123

### Contributor Name

David Linke

### Contributor GitHub

dalito

### Contributor ORCiD

0000-0002-5898-1820

### Contact Name

Nikolaos Moustakas

### Contact ORCiD

0000-0002-6242-2167

### Contact GitHub

nmoust

### Contact Email

nikolaos.moustakas@catalysis.de

### Additional Comments

The most current version of a concept can be accessed so

* https://w3id.org/nfdi4cat/voc4cat_0000123

other/older versions from releases like so

* https://w3id.org/nfdi4cat/voc4cat/v2023-08-17/voc4cat_0000123

Does what I put into the fields match this?

**Comment by cthoyt** [comment]
Thanks @dalito! There were a few things that I had to update for the PR, but this is an excellent contribution.

Regarding the fact that you have versioned IRIs: the Bioregistry doesn't have a specific way for dealing with this at the moment. If you think it's important for people to be able to parse and resolve these, I can imagine we add multiple providers that correspond to these. We can follow up with this

**Comment by cthoyt** [comment]
@dalito see https://bioregistry.io/registry/voc4cat

**Comment by dalito** [comment]
@cthoyt - Thanks for adding this so fast!

I do not expect that many users will to refer to some specific version instead of the latest version. For these special cases they can always use full IRIs including the version.

If the version is added e.g. in this way `voc4cat[v2023-08-17]:0000123` (`prefix[version-specifier]:id`) then I would expect that adding support for this is probably a bigger effort. For us this is not urgent at all.
