### ISSUE TITLE
Update PubMed Central

### ISSUE THREAD

**Issue by sierra-moxon** [biopragmatics/bioregistry#965]
### Prefix

pmc

### Explanation

I am confused about how to interpret the PMC/pmc/PMCID prefix.   It looks like it can expand to two different resources?  Pubmed Central at NCBI and European PMC, and these two resources actually use different local identifier regex patterns to resolve correctly. e.g.: 
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3084216/?tool=pubmed
- https://europepmc.org/article/PMC/3084216 

(On the bioregistry page, this URL actually is written so that the regex works for expansion:  https://europepmc.org/article/PMC3084216 is redirected to https://europepmc.org/article/PMC/3084216 but its not clear to me from the metadata on the `pmc` prefix that this is happening).  Said another way, this URL https://europepmc.org/article/PMC3084216 doesn't resolve?

### Contributor ORCID

0000-0002-8719-7760

## Blocked By

- [x] https://github.com/biopragmatics/bioregistry/issues/967

**Comment by cthoyt** [comment]
It appears that https://europepmc.org/articles/PMC3084216 (note the plural on "article") redirects to https://europepmc.org/article/PMC/3084216, so the Europe PMC site also maintains compatibility with how it's annotated now, including the `PMC` string in the local unique identifier.

I agree that this is a very confusing type of namespace in LUID / banana situation. If we wanted to say that the PMC identifier should actually only be the number, then we would have to use banana normalization logic, which goes beyond the standard prefix normalization that e.g., the `curies` package handles.

Maybe again we should seek out a responsible person from the PMC to try and get an authoritative look at this

**Comment by jeffbeckncbi** [comment]
Thanks to Charlie for looping us in on this discussion. I am the Program Head for Literature at NCBI - the group that runs PubMed and PMC at the US Library of Medicine.

PMC uses the accession id format with the "PMC" prefix. There can also be a version number suffix. So the pattern is "PMC"{Integer}.{version}. An accession without a specific version number should resolve to the highest available or "current" version of the article. 

Compare 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7418728
and 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7418728.1
and even 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7418728,2

To your question, "PMC" is an integral part of the PMC Accession ID, so it should be included. To create a CURIE with the pmc prefix, there will be an apparent redundancy

pmc:PMC7418728
pmc:PMC7418728.1

Europe PMC mirrors most of the content from PMC, and the identifiers are managed by PMC at NCBI/NLM. So the AccessionIds are the same for an article in PMC or when it is distributed through EuropePMC.

**Comment by cthoyt** [comment]
@jeffbeckncbi this is great, thank you for getting in touch. Do you think you could share your ORCID and email address such that we can mark you as the contact for both the PMC and PubMed records?

**Comment by jeffbeckncbi** [comment]
Sure. The email address associated with this github account is beck@ncbi.nlm.nih.gov, but it is much easier to use jbeck@nih.gov. 

... looking up my ORCID ID Identifier ...

https://orcid.org/0000-0002-1798-9797

Jeff

**Comment by cthoyt** [comment]
@sierra-moxon it looks like the resolution to this confusion is that the Europe PMC site makes a implementation decision to store its PMC identifiers in a non-standard form (i.e., as an integer). It therefore redirects from https://europepmc.org/articles/PMC3084216 to https://europepmc.org/article/PMC/3084216 (note `articles` in the first vs `article` in the second). It doesn't appear that full PMC's work in the `article` endpoint.

**Comment by sierra-moxon** [comment]
@cthoyt @jeffbeckncbi - can you confirm that the URI expansion should be to European PMC instead of NCBI in bioregistry?  It does not appear I can reopen this ticket.

**Comment by cthoyt** [comment]
Sorry, I must have overlooked if this was part of the earlier issue. I don't think any of these are RDF-ready URI formats, right?

**Comment by sierra-moxon** [comment]
Also I would like confirmation that "PMC" should be the "preferred" prefix for these identifiers?  Or is "pmc" preferred? 
thanks!

**Comment by sierra-moxon** [comment]
@jeffbeckncbi - can you also comment on: https://github.com/biopragmatics/bioregistry/issues/323 ?  Issue 323 deals with the prefix for PubMed IDs.  (PMID vs. pubmed vs. PUBMED). thanks again!

**Comment by jeffbeckncbi** [comment]
> Also I would like confirmation that "PMC" should be the "preferred" prefix for these identifiers? Or is "pmc" preferred? thanks!

I'm getting confused about what you mean by prefix. "PMC" is part of the Accession ID for PubMed Central Articles. "pmc" should be used for the scheme in the URI.

**Comment by cthoyt** [comment]
@jeffbeckncbi the question is, which is better when using the CURIE syntax:

1. pmc:PMC7418728
2. PMC:PMC7418728
