### ISSUE TITLE
Add prefix [m4i]

### ISSUE THREAD

**Issue by Zack-83** [biopragmatics/bioregistry#970]
### Prefix

m4i

### Name

Metadata4Ing

### Homepage

https://w3id.org/nfdi4ing/metadata4ing/

### Repository

https://git.rwth-aachen.de/nfdi4ing/metadata4ing/metadata4ing/

### Description

The ontology Metadata4Ing is developed within the NFDI Consortium NFDI4Ing with the aim of providing a thorough framework for the semantic description of research data, with a particular focus on engineering sciences and neighbouring disciplines. This ontology allows a description of the whole data generation process (experiment, observation, simulation), embracing the object of investigation, all sample and data manipulation procedures, a summary of the data files and the information contained, and all personal and institutional roles. The subordinate classes and relations can be built according to the two principles of inheritance and modularity. "Inheritance" means that a subclass inherits all properties of its superordinate class, possibly adding some new ones. Modularity means that all expansions are independent of each other; this makes possible for instance to generate expanded ontologies for any possible combinations of method × object of research.

### License

https://creativecommons.org/licenses/by/4.0/ 

### Example Local Unique Identifier

Method

### Regular Expression Pattern for Local Unique Identifier

^\w+$

### URI Format String

http://w3id.org/nfdi4ing/metadata4ing#$1

### Wikidata Property

Q111516803

### Contributor Name

Metadata4Ing Workgroup

### Contributor GitHub

@Zack-83

### Contributor ORCiD

0000-0002-2239-3955

### Contact Name

Giacomo Lanza

### Contact ORCiD

0000-0002-2239-3955

### Contact GitHub

@Zack-83

### Contact Email

giacomo.lanza@ptb.de

**Comment by cthoyt** [comment]
Thanks @Zack-83! We’re not too keen on accepting three character prefixes due to the likelihood of collisions with other prefixes in other domains, so do you think we can directly use metadata4ing as the prefix instead?

**Comment by Zack-83** [comment]
Thanks @cthoyt for the fast response! Actually the prefix has already been in use for one and a half year and is also """registered""" on prefix.cc .

I would like to add to the discussion my co-authors https://github.com/doigl , https://github.com/SArndt-TIB , https://github.com/JohannesLipp .

**Comment by cthoyt** [comment]
@Zack-83 is this developed using a github or other git repository? Can you please share the information on that?

**Comment by Zack-83** [comment]
> @Zack-83 is this developed using a github or other git repository? Can you please share the information on that?

Yes. I added it to the description above: https://git.rwth-aachen.de/nfdi4ing/metadata4ing/metadata4ing/

**Comment by cthoyt** [comment]
@Zack-83 thanks! Just fixing a CI issue then will merge this :)

**Comment by Zack-83** [comment]
Dear @cthoyt , we have some minimum corrections to our entry (full list of contributors, correct hosting institutions). Should I reopen #971 or create a new merge request?

**Comment by cthoyt** [comment]
hi @Zack-83 thanks for being patient over break! Please make a new PR.

Note that the contributor list on Bioregistry is for who made contributions to the Bioregistry record, not the resource the record describes.

**Comment by Zack-83** [comment]
Many thanks @cthoyt . I will do it.
The entry on Bioregistries was mostly prepared by me (together with you), but the ontology is a collective work.
If from your point of view it is preferrable to have only one name under "Contributors", would it be possible to add more names under "Contact"?

**Comment by cthoyt** [comment]
@Zack-83 the job of the Bioregistry record is not to keep track of who contributes to the ontology. The Bioregistry record only keeps track of who contributes to the Bioregistry record. We keep exactly one primary contact person for each prefix - the job of this slot is not to be for credit, but rather to denote a primary responsible person to get in touch with when there are problems. This concept is derived from the OBO Principle on Locus of Authority (https://obofoundry.org/principles/fp-011-locus-of-authority.html) if you want to read more

**Comment by Zack-83** [comment]
Fine. I created the new pull request #1022
