### ISSUE TITLE
Add prefix nih gene id

### ISSUE THREAD

**Issue by cmrn-rhi** [biopragmatics/bioregistry#983]
### Prefix

geneid OR nihgeneid

### Name

National Library of Medicine Gene ID

### Homepage

https://www.ncbi.nlm.nih.gov/gene/

### Repository

bioregistry

### Description

Gene integrates information from a wide range of species. A record may include nomenclature, Reference Sequences (RefSeqs), maps, pathways, variations, phenotypes, and links to genome-, phenotype-, and locus-specific resources worldwide.

### Example Local Unique Identifier

43740574

### Contributor Name

Rhiannon Cameron

### Contributor GitHub

cmrn-rhi

### Contributor ORCiD

0000-0002-9578-0788

**Comment by bgyori** [comment]
Hello @cmrn-rhi thanks for this suggestion! I believe this resource is already covered under https://bioregistry.io/registry/ncbigene, could you check to confirm if that's the same resource you meant?

**Comment by cthoyt** [comment]
Based on the homepage, I believe these are the same. @cmrn-rhi what we can do is add additional synonyms to the record in case you are getting data that is labeled with `nihgeneid` or `geneid` in it

**Comment by cmrn-rhi** [comment]
Great! Yes, I agree these are referring to the same database. Sorry I missed it - I was just searching up the prefixes I had come across in the wild.

I think adding `nihgeneid` as synonym would definitely be helpful as it has come up several times for me. I personally find `geneid` is a bit ambiguous.., but I've also seen it used ([example](https://www.creative-biolabs.com/magic-membrane-protein-sars2-orf7b-expressed-in-cell-free-expression-system-full-length-12233.htm)) so I guess it does make sense to have as a backup synonym.

**Comment by cthoyt** [comment]
Closed in https://github.com/biopragmatics/bioregistry/pull/988
