### ISSUE TITLE
Add prefix for Manufacturers of Vaccines (MVX) code set

### ISSUE THREAD

**Issue by lnanderson** [biopragmatics/bioregistry#986]
### Prefix

mvx

### Name

Manufacturers of Vaccines

### Homepage

https://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=mvx

### Repository

https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.12.227

### Description

The CDC's National Center for Immunization and Respiratory Diseases ([NCIRD](https://www.cdc.gov/ncird/)) developed and maintains HL7 Table 0227, Manufacturers of Vaccines (MVX). It includes both active and inactive manufacturers of vaccines in the US. Inactive MVX codes allow transmission of historical immunization records. When [MVX code is paired with a CVX code](https://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=tradename) (vaccine administered code), the specific trade named vaccine may be indicated.

### License

Apache-2.0 license

### Example Local Unique Identifier

ASZ

### Regular Expression Pattern for Local Unique Identifier

^mvx:\d+$

### URI Format String

https://phinvads.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.12.227&code=ASZ

### Contributor Name

Lindsey Anderson

### Contributor GitHub

lnanderson

### Contributor ORCiD

0000-0002-8741-7823

### Contact Name

 CDC Public Health Information Network Vocabulary Access and Distribution System (PHIN VADS)

### Contact Email

phinvs@cdc.gov

### Additional Comments

Related Collection: [FHIR External Terminologies](https://bioregistry.io/collection/0000009)

Note: Not sure how [this repository](https://github.com/CDCgov/CDC_IIS_Open_Tools/tree/af21ad57891328d9f51f786edd7afc9cd5370286/extract-validator/src/main/resources) links in (please advise).

**Comment by lnanderson** [comment]
@cthoyt see additional comments for collection relevance.

**Comment by cthoyt** [comment]
@lnanderson thanks! Will follow up on this soon
